/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_AbortTransmission_H_
#define	_AbortTransmission_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SRSResourceSetID.h"
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AbortTransmission_PR {
	AbortTransmission_PR_NOTHING,	/* No components present */
	AbortTransmission_PR_sRSResourceSetID,
	AbortTransmission_PR_releaseALL,
	AbortTransmission_PR_choice_extension
} AbortTransmission_PR;

/* Forward declarations */
struct ProtocolIE_SingleContainer;

/* AbortTransmission */
typedef struct AbortTransmission {
	AbortTransmission_PR present;
	union AbortTransmission_u {
		SRSResourceSetID_t	 sRSResourceSetID;
		NULL_t	 releaseALL;
		struct ProtocolIE_SingleContainer	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AbortTransmission_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AbortTransmission;

#ifdef __cplusplus
}
#endif

#endif	/* _AbortTransmission_H_ */
#include <asn_internal.h>
