/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#include "ActiveULBWP.h"

#include "ProtocolExtensionContainer.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_locationAndBandwidth_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 37949)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_txDirectCurrentLocation_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3301)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_subcarrierSpacing_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_cyclicPrefix_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_shift7dot5kHz_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_locationAndBandwidth_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  16,  16,  0,  37949 }	/* (0..37949,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_txDirectCurrentLocation_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  12,  12,  0,  3301 }	/* (0..3301,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_subcarrierSpacing_value2enum_3[] = {
	{ 0,	5,	"kHz15" },
	{ 1,	5,	"kHz30" },
	{ 2,	5,	"kHz60" },
	{ 3,	6,	"kHz120" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_subcarrierSpacing_enum2value_3[] = {
	3,	/* kHz120(3) */
	0,	/* kHz15(0) */
	1,	/* kHz30(1) */
	2	/* kHz60(2) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_subcarrierSpacing_specs_3 = {
	asn_MAP_subcarrierSpacing_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_subcarrierSpacing_enum2value_3,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	5,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_subcarrierSpacing_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_subcarrierSpacing_3 = {
	"subcarrierSpacing",
	"subcarrierSpacing",
	&asn_OP_NativeEnumerated,
	asn_DEF_subcarrierSpacing_tags_3,
	sizeof(asn_DEF_subcarrierSpacing_tags_3)
		/sizeof(asn_DEF_subcarrierSpacing_tags_3[0]) - 1, /* 1 */
	asn_DEF_subcarrierSpacing_tags_3,	/* Same as above */
	sizeof(asn_DEF_subcarrierSpacing_tags_3)
		/sizeof(asn_DEF_subcarrierSpacing_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_subcarrierSpacing_constr_3, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_subcarrierSpacing_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_cyclicPrefix_value2enum_9[] = {
	{ 0,	6,	"normal" },
	{ 1,	8,	"extended" }
};
static const unsigned int asn_MAP_cyclicPrefix_enum2value_9[] = {
	1,	/* extended(1) */
	0	/* normal(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_cyclicPrefix_specs_9 = {
	asn_MAP_cyclicPrefix_value2enum_9,	/* "tag" => N; sorted by tag */
	asn_MAP_cyclicPrefix_enum2value_9,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_cyclicPrefix_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cyclicPrefix_9 = {
	"cyclicPrefix",
	"cyclicPrefix",
	&asn_OP_NativeEnumerated,
	asn_DEF_cyclicPrefix_tags_9,
	sizeof(asn_DEF_cyclicPrefix_tags_9)
		/sizeof(asn_DEF_cyclicPrefix_tags_9[0]) - 1, /* 1 */
	asn_DEF_cyclicPrefix_tags_9,	/* Same as above */
	sizeof(asn_DEF_cyclicPrefix_tags_9)
		/sizeof(asn_DEF_cyclicPrefix_tags_9[0]), /* 2 */
	{ 0, &asn_PER_type_cyclicPrefix_constr_9, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_cyclicPrefix_specs_9	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_shift7dot5kHz_value2enum_13[] = {
	{ 0,	4,	"true" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_shift7dot5kHz_enum2value_13[] = {
	0	/* true(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_shift7dot5kHz_specs_13 = {
	asn_MAP_shift7dot5kHz_value2enum_13,	/* "tag" => N; sorted by tag */
	asn_MAP_shift7dot5kHz_enum2value_13,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	2,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_shift7dot5kHz_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_shift7dot5kHz_13 = {
	"shift7dot5kHz",
	"shift7dot5kHz",
	&asn_OP_NativeEnumerated,
	asn_DEF_shift7dot5kHz_tags_13,
	sizeof(asn_DEF_shift7dot5kHz_tags_13)
		/sizeof(asn_DEF_shift7dot5kHz_tags_13[0]) - 1, /* 1 */
	asn_DEF_shift7dot5kHz_tags_13,	/* Same as above */
	sizeof(asn_DEF_shift7dot5kHz_tags_13)
		/sizeof(asn_DEF_shift7dot5kHz_tags_13[0]), /* 2 */
	{ 0, &asn_PER_type_shift7dot5kHz_constr_13, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_shift7dot5kHz_specs_13	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ActiveULBWP_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveULBWP, locationAndBandwidth),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_locationAndBandwidth_constr_2,  memb_locationAndBandwidth_constraint_1 },
		0, 0, /* No default value */
		"locationAndBandwidth"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveULBWP, subcarrierSpacing),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_subcarrierSpacing_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subcarrierSpacing"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveULBWP, cyclicPrefix),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_cyclicPrefix_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cyclicPrefix"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveULBWP, txDirectCurrentLocation),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_txDirectCurrentLocation_constr_12,  memb_txDirectCurrentLocation_constraint_1 },
		0, 0, /* No default value */
		"txDirectCurrentLocation"
		},
	{ ATF_POINTER, 1, offsetof(struct ActiveULBWP, shift7dot5kHz),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_shift7dot5kHz_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"shift7dot5kHz"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveULBWP, sRSConfig),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SRSConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sRSConfig"
		},
	{ ATF_POINTER, 1, offsetof(struct ActiveULBWP, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_10676P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ActiveULBWP_oms_1[] = { 4, 6 };
static const ber_tlv_tag_t asn_DEF_ActiveULBWP_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ActiveULBWP_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* locationAndBandwidth */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* subcarrierSpacing */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cyclicPrefix */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* txDirectCurrentLocation */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* shift7dot5kHz */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* sRSConfig */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ActiveULBWP_specs_1 = {
	sizeof(struct ActiveULBWP),
	offsetof(struct ActiveULBWP, _asn_ctx),
	asn_MAP_ActiveULBWP_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_ActiveULBWP_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ActiveULBWP = {
	"ActiveULBWP",
	"ActiveULBWP",
	&asn_OP_SEQUENCE,
	asn_DEF_ActiveULBWP_tags_1,
	sizeof(asn_DEF_ActiveULBWP_tags_1)
		/sizeof(asn_DEF_ActiveULBWP_tags_1[0]), /* 1 */
	asn_DEF_ActiveULBWP_tags_1,	/* Same as above */
	sizeof(asn_DEF_ActiveULBWP_tags_1)
		/sizeof(asn_DEF_ActiveULBWP_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ActiveULBWP_1,
	7,	/* Elements count */
	&asn_SPC_ActiveULBWP_specs_1	/* Additional specs */
};

