/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_AdditionalDuplicationIndication_H_
#define	_AdditionalDuplicationIndication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdditionalDuplicationIndication {
	AdditionalDuplicationIndication_three	= 0,
	AdditionalDuplicationIndication_four	= 1
	/*
	 * Enumeration is extensible
	 */
} e_AdditionalDuplicationIndication;

/* AdditionalDuplicationIndication */
typedef long	 AdditionalDuplicationIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdditionalDuplicationIndication;
asn_struct_free_f AdditionalDuplicationIndication_free;
asn_struct_print_f AdditionalDuplicationIndication_print;
asn_constr_check_f AdditionalDuplicationIndication_constraint;
ber_type_decoder_f AdditionalDuplicationIndication_decode_ber;
der_type_encoder_f AdditionalDuplicationIndication_encode_der;
xer_type_decoder_f AdditionalDuplicationIndication_decode_xer;
xer_type_encoder_f AdditionalDuplicationIndication_encode_xer;
oer_type_decoder_f AdditionalDuplicationIndication_decode_oer;
oer_type_encoder_f AdditionalDuplicationIndication_encode_oer;
per_type_decoder_f AdditionalDuplicationIndication_decode_uper;
per_type_encoder_f AdditionalDuplicationIndication_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AdditionalDuplicationIndication_H_ */
#include <asn_internal.h>
