/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_AdditionalPDCPDuplicationTNL_List_H_
#define	_AdditionalPDCPDuplicationTNL_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AdditionalPDCPDuplicationTNL_Item;

/* AdditionalPDCPDuplicationTNL-List */
typedef struct AdditionalPDCPDuplicationTNL_List {
	A_SEQUENCE_OF(struct AdditionalPDCPDuplicationTNL_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdditionalPDCPDuplicationTNL_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdditionalPDCPDuplicationTNL_List;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AdditionalPDCPDuplicationTNL-Item.h"

#endif	/* _AdditionalPDCPDuplicationTNL_List_H_ */
#include <asn_internal.h>
