/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_AlternativeQoSParaSetList_H_
#define	_AlternativeQoSParaSetList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlternativeQoSParaSetItem;

/* AlternativeQoSParaSetList */
typedef struct AlternativeQoSParaSetList {
	A_SEQUENCE_OF(struct AlternativeQoSParaSetItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlternativeQoSParaSetList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlternativeQoSParaSetList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlternativeQoSParaSetItem.h"

#endif	/* _AlternativeQoSParaSetList_H_ */
#include <asn_internal.h>
