/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_AperiodicSRSResourceTrigger_H_
#define	_AperiodicSRSResourceTrigger_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AperiodicSRSResourceTrigger */
typedef long	 AperiodicSRSResourceTrigger_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AperiodicSRSResourceTrigger_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AperiodicSRSResourceTrigger;
asn_struct_free_f AperiodicSRSResourceTrigger_free;
asn_struct_print_f AperiodicSRSResourceTrigger_print;
asn_constr_check_f AperiodicSRSResourceTrigger_constraint;
ber_type_decoder_f AperiodicSRSResourceTrigger_decode_ber;
der_type_encoder_f AperiodicSRSResourceTrigger_encode_der;
xer_type_decoder_f AperiodicSRSResourceTrigger_decode_xer;
xer_type_encoder_f AperiodicSRSResourceTrigger_encode_xer;
oer_type_decoder_f AperiodicSRSResourceTrigger_decode_oer;
oer_type_encoder_f AperiodicSRSResourceTrigger_encode_oer;
per_type_decoder_f AperiodicSRSResourceTrigger_decode_uper;
per_type_encoder_f AperiodicSRSResourceTrigger_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AperiodicSRSResourceTrigger_H_ */
#include <asn_internal.h>
