/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_BH_Routing_Information_Removed_List_Item_H_
#define	_BH_Routing_Information_Removed_List_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BAPRoutingID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* BH-Routing-Information-Removed-List-Item */
typedef struct BH_Routing_Information_Removed_List_Item {
	BAPRoutingID_t	 bAPRoutingID;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BH_Routing_Information_Removed_List_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BH_Routing_Information_Removed_List_Item;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _BH_Routing_Information_Removed_List_Item_H_ */
#include <asn_internal.h>
