/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_BPLMN_ID_Info_List_H_
#define	_BPLMN_ID_Info_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BPLMN_ID_Info_Item;

/* BPLMN-ID-Info-List */
typedef struct BPLMN_ID_Info_List {
	A_SEQUENCE_OF(struct BPLMN_ID_Info_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BPLMN_ID_Info_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BPLMN_ID_Info_List;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BPLMN-ID-Info-Item.h"

#endif	/* _BPLMN_ID_Info_List_H_ */
#include <asn_internal.h>
