/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_CellToReportList_H_
#define	_CellToReportList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CellToReportItem;

/* CellToReportList */
typedef struct CellToReportList {
	A_SEQUENCE_OF(struct CellToReportItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellToReportList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellToReportList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CellToReportItem.h"

#endif	/* _CellToReportList_H_ */
#include <asn_internal.h>
