/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_CHO_Probability_H_
#define	_CHO_Probability_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CHO-Probability */
typedef long	 CHO_Probability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CHO_Probability;
asn_struct_free_f CHO_Probability_free;
asn_struct_print_f CHO_Probability_print;
asn_constr_check_f CHO_Probability_constraint;
ber_type_decoder_f CHO_Probability_decode_ber;
der_type_encoder_f CHO_Probability_encode_der;
xer_type_decoder_f CHO_Probability_decode_xer;
xer_type_encoder_f CHO_Probability_encode_xer;
per_type_decoder_f CHO_Probability_decode_uper;
per_type_encoder_f CHO_Probability_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CHO_Probability_H_ */
#include <asn_internal.h>
