/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_ConditionalIntraDUMobilityInformation_H_
#define	_ConditionalIntraDUMobilityInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CHOtrigger-IntraDU.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TargetCellList;
struct ProtocolExtensionContainer;

/* ConditionalIntraDUMobilityInformation */
typedef struct ConditionalIntraDUMobilityInformation {
	CHOtrigger_IntraDU_t	 cho_trigger;
	struct TargetCellList	*targetCellsTocancel	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConditionalIntraDUMobilityInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConditionalIntraDUMobilityInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TargetCellList.h"
#include "ProtocolExtensionContainer.h"

#endif	/* _ConditionalIntraDUMobilityInformation_H_ */
#include <asn_internal.h>
