/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_ConditionalInterDUMobilityInformation_H_
#define	_ConditionalInterDUMobilityInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CHOtrigger-InterDU.h"
#include "GNB-DU-UE-F1AP-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* ConditionalInterDUMobilityInformation */
typedef struct ConditionalInterDUMobilityInformation {
	CHOtrigger_InterDU_t	 cho_trigger;
	GNB_DU_UE_F1AP_ID_t	*targetgNB_DUUEF1APID	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConditionalInterDUMobilityInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConditionalInterDUMobilityInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _ConditionalInterDUMobilityInformation_H_ */
#include <asn_internal.h>
