/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_CUDURadioInformationType_H_
#define	_CUDURadioInformationType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CUDURIMInformation.h"
#include "ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CUDURadioInformationType_PR {
	CUDURadioInformationType_PR_NOTHING,	/* No components present */
	CUDURadioInformationType_PR_rIM,
	CUDURadioInformationType_PR_choice_extension
} CUDURadioInformationType_PR;

/* CUDURadioInformationType */
typedef struct CUDURadioInformationType {
	CUDURadioInformationType_PR present;
	union CUDURadioInformationType_u {
		CUDURIMInformation_t	 rIM;
		ProtocolIE_SingleContainer_120P0_t	 choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CUDURadioInformationType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CUDURadioInformationType;

#ifdef __cplusplus
}
#endif

#endif	/* _CUDURadioInformationType_H_ */
#include <asn_internal.h>
