/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_CUDURadioInformationType_H_
#define	_CUDURadioInformationType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CUDURadioInformationType_PR {
	CUDURadioInformationType_PR_NOTHING,	/* No components present */
	CUDURadioInformationType_PR_rIM,
	CUDURadioInformationType_PR_choice_extension
} CUDURadioInformationType_PR;

/* Forward declarations */
struct CUDURIMInformation;
struct ProtocolIE_SingleContainer;

/* CUDURadioInformationType */
typedef struct CUDURadioInformationType {
	CUDURadioInformationType_PR present;
	union CUDURadioInformationType_u {
		struct CUDURIMInformation	*rIM;
		struct ProtocolIE_SingleContainer	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CUDURadioInformationType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CUDURadioInformationType;

#ifdef __cplusplus
}
#endif

#endif	/* _CUDURadioInformationType_H_ */
#include <asn_internal.h>
