/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#include "DL-PRSResourceSetARPLocation.h"

static asn_oer_constraints_t asn_OER_type_DL_PRSResourceSetARPLocation_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_DL_PRSResourceSetARPLocation_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_DL_PRSResourceSetARPLocation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DL_PRSResourceSetARPLocation, choice.relativeGeodeticLocation),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RelativeGeodeticLocation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"relativeGeodeticLocation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_PRSResourceSetARPLocation, choice.relativeCartesianLocation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RelativeCartesianLocation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"relativeCartesianLocation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_PRSResourceSetARPLocation, choice.choice_Extension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolIE_SingleContainer_120P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"choice-Extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_DL_PRSResourceSetARPLocation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* relativeGeodeticLocation */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* relativeCartesianLocation */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* choice-Extension */
};
asn_CHOICE_specifics_t asn_SPC_DL_PRSResourceSetARPLocation_specs_1 = {
	sizeof(struct DL_PRSResourceSetARPLocation),
	offsetof(struct DL_PRSResourceSetARPLocation, _asn_ctx),
	offsetof(struct DL_PRSResourceSetARPLocation, present),
	sizeof(((struct DL_PRSResourceSetARPLocation *)0)->present),
	asn_MAP_DL_PRSResourceSetARPLocation_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_DL_PRSResourceSetARPLocation = {
	"DL-PRSResourceSetARPLocation",
	"DL-PRSResourceSetARPLocation",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_DL_PRSResourceSetARPLocation_constr_1, &asn_PER_type_DL_PRSResourceSetARPLocation_constr_1, CHOICE_constraint },
	asn_MBR_DL_PRSResourceSetARPLocation_1,
	3,	/* Elements count */
	&asn_SPC_DL_PRSResourceSetARPLocation_specs_1	/* Additional specs */
};

