/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_DUCURadioInformationType_H_
#define	_DUCURadioInformationType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DUCURadioInformationType_PR {
	DUCURadioInformationType_PR_NOTHING,	/* No components present */
	DUCURadioInformationType_PR_rIM,
	DUCURadioInformationType_PR_choice_extension
} DUCURadioInformationType_PR;

/* Forward declarations */
struct DUCURIMInformation;
struct ProtocolIE_SingleContainer;

/* DUCURadioInformationType */
typedef struct DUCURadioInformationType {
	DUCURadioInformationType_PR present;
	union DUCURadioInformationType_u {
		struct DUCURIMInformation	*rIM;
		struct ProtocolIE_SingleContainer	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DUCURadioInformationType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DUCURadioInformationType;

#ifdef __cplusplus
}
#endif

#endif	/* _DUCURadioInformationType_H_ */
#include <asn_internal.h>
