/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_DUCURadioInformationType_H_
#define	_DUCURadioInformationType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DUCURIMInformation.h"
#include "ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DUCURadioInformationType_PR {
	DUCURadioInformationType_PR_NOTHING,	/* No components present */
	DUCURadioInformationType_PR_rIM,
	DUCURadioInformationType_PR_choice_extension
} DUCURadioInformationType_PR;

/* DUCURadioInformationType */
typedef struct DUCURadioInformationType {
	DUCURadioInformationType_PR present;
	union DUCURadioInformationType_u {
		DUCURIMInformation_t	 rIM;
		ProtocolIE_SingleContainer_120P0_t	 choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DUCURadioInformationType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DUCURadioInformationType;

#ifdef __cplusplus
}
#endif

#endif	/* _DUCURadioInformationType_H_ */
#include <asn_internal.h>
