/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_DUF_Slot_Config_Item_H_
#define	_DUF_Slot_Config_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ExplicitFormat.h"
#include "ImplicitFormat.h"
#include "ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DUF_Slot_Config_Item_PR {
	DUF_Slot_Config_Item_PR_NOTHING,	/* No components present */
	DUF_Slot_Config_Item_PR_explicitFormat,
	DUF_Slot_Config_Item_PR_implicitFormat,
	DUF_Slot_Config_Item_PR_choice_extension
} DUF_Slot_Config_Item_PR;

/* DUF-Slot-Config-Item */
typedef struct DUF_Slot_Config_Item {
	DUF_Slot_Config_Item_PR present;
	union DUF_Slot_Config_Item_u {
		ExplicitFormat_t	 explicitFormat;
		ImplicitFormat_t	 implicitFormat;
		ProtocolIE_SingleContainer_120P0_t	 choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DUF_Slot_Config_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DUF_Slot_Config_Item;
extern asn_CHOICE_specifics_t asn_SPC_DUF_Slot_Config_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_DUF_Slot_Config_Item_1[3];
extern asn_per_constraints_t asn_PER_type_DUF_Slot_Config_Item_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _DUF_Slot_Config_Item_H_ */
#include <asn_internal.h>
