/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_E_CID_MeasurementPeriodicity_H_
#define	_E_CID_MeasurementPeriodicity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E_CID_MeasurementPeriodicity {
	E_CID_MeasurementPeriodicity_ms120	= 0,
	E_CID_MeasurementPeriodicity_ms240	= 1,
	E_CID_MeasurementPeriodicity_ms480	= 2,
	E_CID_MeasurementPeriodicity_ms640	= 3,
	E_CID_MeasurementPeriodicity_ms1024	= 4,
	E_CID_MeasurementPeriodicity_ms2048	= 5,
	E_CID_MeasurementPeriodicity_ms5120	= 6,
	E_CID_MeasurementPeriodicity_ms10240	= 7,
	E_CID_MeasurementPeriodicity_min1	= 8,
	E_CID_MeasurementPeriodicity_min6	= 9,
	E_CID_MeasurementPeriodicity_min12	= 10,
	E_CID_MeasurementPeriodicity_min30	= 11,
	E_CID_MeasurementPeriodicity_min60	= 12
	/*
	 * Enumeration is extensible
	 */
} e_E_CID_MeasurementPeriodicity;

/* E-CID-MeasurementPeriodicity */
typedef long	 E_CID_MeasurementPeriodicity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_CID_MeasurementPeriodicity;
asn_struct_free_f E_CID_MeasurementPeriodicity_free;
asn_struct_print_f E_CID_MeasurementPeriodicity_print;
asn_constr_check_f E_CID_MeasurementPeriodicity_constraint;
ber_type_decoder_f E_CID_MeasurementPeriodicity_decode_ber;
der_type_encoder_f E_CID_MeasurementPeriodicity_encode_der;
xer_type_decoder_f E_CID_MeasurementPeriodicity_decode_xer;
xer_type_encoder_f E_CID_MeasurementPeriodicity_encode_xer;
oer_type_decoder_f E_CID_MeasurementPeriodicity_decode_oer;
oer_type_encoder_f E_CID_MeasurementPeriodicity_encode_oer;
per_type_decoder_f E_CID_MeasurementPeriodicity_decode_uper;
per_type_encoder_f E_CID_MeasurementPeriodicity_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _E_CID_MeasurementPeriodicity_H_ */
#include <asn_internal.h>
