/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_E_CID_MeasuredResults_Item_H_
#define	_E_CID_MeasuredResults_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E-CID-MeasuredResults-Value.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* E-CID-MeasuredResults-Item */
typedef struct E_CID_MeasuredResults_Item {
	E_CID_MeasuredResults_Value_t	 e_CID_MeasuredResults_Value;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_CID_MeasuredResults_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_CID_MeasuredResults_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_E_CID_MeasuredResults_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_E_CID_MeasuredResults_Item_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _E_CID_MeasuredResults_Item_H_ */
#include <asn_internal.h>
