/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#include "E-CID-MeasuredResults-Value.h"

#include "UL-AoA.h"
#include "ProtocolIE-SingleContainer.h"
asn_per_constraints_t asn_PER_type_E_CID_MeasuredResults_Value_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_E_CID_MeasuredResults_Value_1[] = {
	{ ATF_POINTER, 0, offsetof(struct E_CID_MeasuredResults_Value, choice.valueAngleofArrivalNR),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_AoA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"valueAngleofArrivalNR"
		},
	{ ATF_POINTER, 0, offsetof(struct E_CID_MeasuredResults_Value, choice.choice_extension),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolIE_SingleContainer_10642P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"choice-extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_E_CID_MeasuredResults_Value_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* valueAngleofArrivalNR */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* choice-extension */
};
asn_CHOICE_specifics_t asn_SPC_E_CID_MeasuredResults_Value_specs_1 = {
	sizeof(struct E_CID_MeasuredResults_Value),
	offsetof(struct E_CID_MeasuredResults_Value, _asn_ctx),
	offsetof(struct E_CID_MeasuredResults_Value, present),
	sizeof(((struct E_CID_MeasuredResults_Value *)0)->present),
	asn_MAP_E_CID_MeasuredResults_Value_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_E_CID_MeasuredResults_Value = {
	"E-CID-MeasuredResults-Value",
	"E-CID-MeasuredResults-Value",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_E_CID_MeasuredResults_Value_constr_1, CHOICE_constraint },
	asn_MBR_E_CID_MeasuredResults_Value_1,
	2,	/* Elements count */
	&asn_SPC_E_CID_MeasuredResults_Value_specs_1	/* Additional specs */
};

