/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_EUTRA_Coex_Mode_Info_H_
#define	_EUTRA_Coex_Mode_Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EUTRA-Coex-FDD-Info.h"
#include "EUTRA-Coex-TDD-Info.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EUTRA_Coex_Mode_Info_PR {
	EUTRA_Coex_Mode_Info_PR_NOTHING,	/* No components present */
	EUTRA_Coex_Mode_Info_PR_fDD,
	EUTRA_Coex_Mode_Info_PR_tDD
	/* Extensions may appear below */
	
} EUTRA_Coex_Mode_Info_PR;

/* EUTRA-Coex-Mode-Info */
typedef struct EUTRA_Coex_Mode_Info {
	EUTRA_Coex_Mode_Info_PR present;
	union EUTRA_Coex_Mode_Info_u {
		EUTRA_Coex_FDD_Info_t	 fDD;
		EUTRA_Coex_TDD_Info_t	 tDD;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRA_Coex_Mode_Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EUTRA_Coex_Mode_Info;
extern asn_CHOICE_specifics_t asn_SPC_EUTRA_Coex_Mode_Info_specs_1;
extern asn_TYPE_member_t asn_MBR_EUTRA_Coex_Mode_Info_1[2];
extern asn_per_constraints_t asn_PER_type_EUTRA_Coex_Mode_Info_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _EUTRA_Coex_Mode_Info_H_ */
#include <asn_internal.h>
