/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_Extended_GNB_CU_Name_H_
#define	_Extended_GNB_CU_Name_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GNB-CU-NameVisibleString.h"
#include "GNB-CU-NameUTF8String.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* Extended-GNB-CU-Name */
typedef struct Extended_GNB_CU_Name {
	GNB_CU_NameVisibleString_t	*gNB_CU_NameVisibleString	/* OPTIONAL */;
	GNB_CU_NameUTF8String_t	*gNB_CU_NameUTF8String	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Extended_GNB_CU_Name_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Extended_GNB_CU_Name;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _Extended_GNB_CU_Name_H_ */
#include <asn_internal.h>
