/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_FR2_Bandwidth_H_
#define	_FR2_Bandwidth_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FR2_Bandwidth {
	FR2_Bandwidth_bw50	= 0,
	FR2_Bandwidth_bw100	= 1,
	FR2_Bandwidth_bw200	= 2,
	FR2_Bandwidth_bw400	= 3
	/*
	 * Enumeration is extensible
	 */
} e_FR2_Bandwidth;

/* FR2-Bandwidth */
typedef long	 FR2_Bandwidth_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FR2_Bandwidth_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FR2_Bandwidth;
extern const asn_INTEGER_specifics_t asn_SPC_FR2_Bandwidth_specs_1;
asn_struct_free_f FR2_Bandwidth_free;
asn_struct_print_f FR2_Bandwidth_print;
asn_constr_check_f FR2_Bandwidth_constraint;
ber_type_decoder_f FR2_Bandwidth_decode_ber;
der_type_encoder_f FR2_Bandwidth_encode_der;
xer_type_decoder_f FR2_Bandwidth_decode_xer;
xer_type_encoder_f FR2_Bandwidth_encode_xer;
per_type_decoder_f FR2_Bandwidth_decode_uper;
per_type_encoder_f FR2_Bandwidth_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FR2_Bandwidth_H_ */
#include <asn_internal.h>
