/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_GNB_DU_NameVisibleString_H_
#define	_GNB_DU_NameVisibleString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GNB-DU-NameVisibleString */
typedef VisibleString_t	 GNB_DU_NameVisibleString_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_GNB_DU_NameVisibleString_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_GNB_DU_NameVisibleString;
asn_struct_free_f GNB_DU_NameVisibleString_free;
asn_struct_print_f GNB_DU_NameVisibleString_print;
asn_constr_check_f GNB_DU_NameVisibleString_constraint;
ber_type_decoder_f GNB_DU_NameVisibleString_decode_ber;
der_type_encoder_f GNB_DU_NameVisibleString_encode_der;
xer_type_decoder_f GNB_DU_NameVisibleString_decode_xer;
xer_type_encoder_f GNB_DU_NameVisibleString_encode_xer;
per_type_decoder_f GNB_DU_NameVisibleString_decode_uper;
per_type_encoder_f GNB_DU_NameVisibleString_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _GNB_DU_NameVisibleString_H_ */
#include <asn_internal.h>
