/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_GNB_DU_TNL_Association_To_Remove_Item_H_
#define	_GNB_DU_TNL_Association_To_Remove_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CP-TransportLayerAddress.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CP_TransportLayerAddress;
struct ProtocolExtensionContainer;

/* GNB-DU-TNL-Association-To-Remove-Item */
typedef struct GNB_DU_TNL_Association_To_Remove_Item {
	CP_TransportLayerAddress_t	 tNLAssociationTransportLayerAddress;
	struct CP_TransportLayerAddress	*tNLAssociationTransportLayerAddressgNBCU	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_DU_TNL_Association_To_Remove_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GNB_DU_TNL_Association_To_Remove_Item;

#ifdef __cplusplus
}
#endif

#endif	/* _GNB_DU_TNL_Association_To_Remove_Item_H_ */
#include <asn_internal.h>
