/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_GNBCUMeasurementID_H_
#define	_GNBCUMeasurementID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GNBCUMeasurementID */
typedef long	 GNBCUMeasurementID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GNBCUMeasurementID;
asn_struct_free_f GNBCUMeasurementID_free;
asn_struct_print_f GNBCUMeasurementID_print;
asn_constr_check_f GNBCUMeasurementID_constraint;
ber_type_decoder_f GNBCUMeasurementID_decode_ber;
der_type_encoder_f GNBCUMeasurementID_encode_der;
xer_type_decoder_f GNBCUMeasurementID_decode_xer;
xer_type_encoder_f GNBCUMeasurementID_encode_xer;
oer_type_decoder_f GNBCUMeasurementID_decode_oer;
oer_type_encoder_f GNBCUMeasurementID_encode_oer;
per_type_decoder_f GNBCUMeasurementID_decode_uper;
per_type_encoder_f GNBCUMeasurementID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _GNBCUMeasurementID_H_ */
#include <asn_internal.h>
