/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_GNBDUMeasurementID_H_
#define	_GNBDUMeasurementID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GNBDUMeasurementID */
typedef long	 GNBDUMeasurementID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GNBDUMeasurementID;
asn_struct_free_f GNBDUMeasurementID_free;
asn_struct_print_f GNBDUMeasurementID_print;
asn_constr_check_f GNBDUMeasurementID_constraint;
ber_type_decoder_f GNBDUMeasurementID_decode_ber;
der_type_encoder_f GNBDUMeasurementID_encode_der;
xer_type_decoder_f GNBDUMeasurementID_decode_xer;
xer_type_encoder_f GNBDUMeasurementID_encode_xer;
per_type_decoder_f GNBDUMeasurementID_decode_uper;
per_type_encoder_f GNBDUMeasurementID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _GNBDUMeasurementID_H_ */
#include <asn_internal.h>
