/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_IAB_Info_IAB_donor_CU_H_
#define	_IAB_Info_IAB_donor_CU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IAB_STC_Info;
struct ProtocolExtensionContainer;

/* IAB-Info-IAB-donor-CU */
typedef struct IAB_Info_IAB_donor_CU {
	struct IAB_STC_Info	*iAB_STC_Info	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IAB_Info_IAB_donor_CU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IAB_Info_IAB_donor_CU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IAB-STC-Info.h"
#include "ProtocolExtensionContainer.h"

#endif	/* _IAB_Info_IAB_donor_CU_H_ */
#include <asn_internal.h>
