/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_IAB_Allocated_TNL_Address_Item_H_
#define	_IAB_Allocated_TNL_Address_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IABTNLAddress.h"
#include "IABTNLAddressUsage.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* IAB-Allocated-TNL-Address-Item */
typedef struct IAB_Allocated_TNL_Address_Item {
	IABTNLAddress_t	 iABTNLAddress;
	IABTNLAddressUsage_t	*iABTNLAddressUsage	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IAB_Allocated_TNL_Address_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IAB_Allocated_TNL_Address_Item;

#ifdef __cplusplus
}
#endif

#endif	/* _IAB_Allocated_TNL_Address_Item_H_ */
#include <asn_internal.h>
