/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_IAB_Barred_H_
#define	_IAB_Barred_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IAB_Barred {
	IAB_Barred_barred	= 0,
	IAB_Barred_not_barred	= 1
	/*
	 * Enumeration is extensible
	 */
} e_IAB_Barred;

/* IAB-Barred */
typedef long	 IAB_Barred_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IAB_Barred;
asn_struct_free_f IAB_Barred_free;
asn_struct_print_f IAB_Barred_print;
asn_constr_check_f IAB_Barred_constraint;
ber_type_decoder_f IAB_Barred_decode_ber;
der_type_encoder_f IAB_Barred_encode_der;
xer_type_decoder_f IAB_Barred_decode_xer;
xer_type_encoder_f IAB_Barred_encode_xer;
per_type_decoder_f IAB_Barred_decode_uper;
per_type_encoder_f IAB_Barred_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _IAB_Barred_H_ */
#include <asn_internal.h>
