/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_IABIPv6RequestType_H_
#define	_IABIPv6RequestType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IABTNLAddressesRequested.h"
#include "ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IABIPv6RequestType_PR {
	IABIPv6RequestType_PR_NOTHING,	/* No components present */
	IABIPv6RequestType_PR_iPv6Address,
	IABIPv6RequestType_PR_iPv6Prefix,
	IABIPv6RequestType_PR_choice_extension
} IABIPv6RequestType_PR;

/* IABIPv6RequestType */
typedef struct IABIPv6RequestType {
	IABIPv6RequestType_PR present;
	union IABIPv6RequestType_u {
		IABTNLAddressesRequested_t	 iPv6Address;
		IABTNLAddressesRequested_t	 iPv6Prefix;
		ProtocolIE_SingleContainer_120P0_t	 choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IABIPv6RequestType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IABIPv6RequestType;

#ifdef __cplusplus
}
#endif

#endif	/* _IABIPv6RequestType_H_ */
#include <asn_internal.h>
