/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_IABIPv6RequestType_H_
#define	_IABIPv6RequestType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IABIPv6RequestType_PR {
	IABIPv6RequestType_PR_NOTHING,	/* No components present */
	IABIPv6RequestType_PR_iPv6Address,
	IABIPv6RequestType_PR_iPv6Prefix,
	IABIPv6RequestType_PR_choice_extension
} IABIPv6RequestType_PR;

/* Forward declarations */
struct IABTNLAddressesRequested;
struct ProtocolIE_SingleContainer;

/* IABIPv6RequestType */
typedef struct IABIPv6RequestType {
	IABIPv6RequestType_PR present;
	union IABIPv6RequestType_u {
		struct IABTNLAddressesRequested	*iPv6Address;
		struct IABTNLAddressesRequested	*iPv6Prefix;
		struct ProtocolIE_SingleContainer	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IABIPv6RequestType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IABIPv6RequestType;

#ifdef __cplusplus
}
#endif

#endif	/* _IABIPv6RequestType_H_ */
#include <asn_internal.h>
