/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-PDU-Contents"
 * 	found in "F1AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_IABUPConfigurationUpdateRequest_H_
#define	_IABUPConfigurationUpdateRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-Container.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IABUPConfigurationUpdateRequest */
typedef struct IABUPConfigurationUpdateRequest {
	ProtocolIE_Container_117P0_t	 protocolIEs;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IABUPConfigurationUpdateRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IABUPConfigurationUpdateRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _IABUPConfigurationUpdateRequest_H_ */
#include <asn_internal.h>
