/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_IABv4AddressesRequested_H_
#define	_IABv4AddressesRequested_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IABTNLAddressesRequested.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* IABv4AddressesRequested */
typedef struct IABv4AddressesRequested {
	IABTNLAddressesRequested_t	 iABv4AddressesRequested;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IABv4AddressesRequested_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IABv4AddressesRequested;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _IABv4AddressesRequested_H_ */
#include <asn_internal.h>
