/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-PDU-Descriptions"
 * 	found in "F1AP-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#include "InitiatingMessage.h"

static const long asn_VAL_1_id_Reset = 0;
static const long asn_VAL_1_reject = 0;
static const long asn_VAL_2_id_F1Setup = 1;
static const long asn_VAL_2_reject = 0;
static const long asn_VAL_3_id_gNBDUConfigurationUpdate = 3;
static const long asn_VAL_3_reject = 0;
static const long asn_VAL_4_id_gNBCUConfigurationUpdate = 4;
static const long asn_VAL_4_reject = 0;
static const long asn_VAL_5_id_UEContextSetup = 5;
static const long asn_VAL_5_reject = 0;
static const long asn_VAL_6_id_UEContextRelease = 6;
static const long asn_VAL_6_reject = 0;
static const long asn_VAL_7_id_UEContextModification = 7;
static const long asn_VAL_7_reject = 0;
static const long asn_VAL_8_id_UEContextModificationRequired = 8;
static const long asn_VAL_8_reject = 0;
static const long asn_VAL_9_id_WriteReplaceWarning = 20;
static const long asn_VAL_9_reject = 0;
static const long asn_VAL_10_id_PWSCancel = 21;
static const long asn_VAL_10_reject = 0;
static const long asn_VAL_11_id_GNBDUResourceCoordination = 16;
static const long asn_VAL_11_reject = 0;
static const long asn_VAL_12_id_F1Removal = 26;
static const long asn_VAL_12_reject = 0;
static const long asn_VAL_13_id_BAPMappingConfiguration = 32;
static const long asn_VAL_13_reject = 0;
static const long asn_VAL_14_id_GNBDUResourceConfiguration = 33;
static const long asn_VAL_14_reject = 0;
static const long asn_VAL_15_id_IABTNLAddressAllocation = 34;
static const long asn_VAL_15_reject = 0;
static const long asn_VAL_16_id_IABUPConfigurationUpdate = 35;
static const long asn_VAL_16_reject = 0;
static const long asn_VAL_17_id_resourceStatusReportingInitiation = 36;
static const long asn_VAL_17_reject = 0;
static const long asn_VAL_18_id_PositioningMeasurementExchange = 41;
static const long asn_VAL_18_reject = 0;
static const long asn_VAL_19_id_TRPInformationExchange = 48;
static const long asn_VAL_19_reject = 0;
static const long asn_VAL_20_id_PositioningInformationExchange = 49;
static const long asn_VAL_20_reject = 0;
static const long asn_VAL_21_id_PositioningActivation = 50;
static const long asn_VAL_21_reject = 0;
static const long asn_VAL_22_id_E_CIDMeasurementInitiation = 52;
static const long asn_VAL_22_reject = 0;
static const long asn_VAL_23_id_ErrorIndication = 2;
static const long asn_VAL_23_ignore = 1;
static const long asn_VAL_24_id_UEContextReleaseRequest = 10;
static const long asn_VAL_24_ignore = 1;
static const long asn_VAL_25_id_DLRRCMessageTransfer = 12;
static const long asn_VAL_25_ignore = 1;
static const long asn_VAL_26_id_ULRRCMessageTransfer = 13;
static const long asn_VAL_26_ignore = 1;
static const long asn_VAL_27_id_UEInactivityNotification = 15;
static const long asn_VAL_27_ignore = 1;
static const long asn_VAL_28_id_privateMessage = 14;
static const long asn_VAL_28_ignore = 1;
static const long asn_VAL_29_id_InitialULRRCMessageTransfer = 11;
static const long asn_VAL_29_ignore = 1;
static const long asn_VAL_30_id_SystemInformationDeliveryCommand = 17;
static const long asn_VAL_30_ignore = 1;
static const long asn_VAL_31_id_Paging = 18;
static const long asn_VAL_31_ignore = 1;
static const long asn_VAL_32_id_Notify = 19;
static const long asn_VAL_32_ignore = 1;
static const long asn_VAL_33_id_PWSRestartIndication = 22;
static const long asn_VAL_33_ignore = 1;
static const long asn_VAL_34_id_PWSFailureIndication = 23;
static const long asn_VAL_34_ignore = 1;
static const long asn_VAL_35_id_GNBDUStatusIndication = 24;
static const long asn_VAL_35_ignore = 1;
static const long asn_VAL_36_id_RRCDeliveryReport = 25;
static const long asn_VAL_36_ignore = 1;
static const long asn_VAL_37_id_NetworkAccessRateReduction = 27;
static const long asn_VAL_37_ignore = 1;
static const long asn_VAL_38_id_TraceStart = 28;
static const long asn_VAL_38_ignore = 1;
static const long asn_VAL_39_id_DeactivateTrace = 29;
static const long asn_VAL_39_ignore = 1;
static const long asn_VAL_40_id_DUCURadioInformationTransfer = 30;
static const long asn_VAL_40_ignore = 1;
static const long asn_VAL_41_id_CUDURadioInformationTransfer = 31;
static const long asn_VAL_41_ignore = 1;
static const long asn_VAL_42_id_resourceStatusReporting = 37;
static const long asn_VAL_42_ignore = 1;
static const long asn_VAL_43_id_accessAndMobilityIndication = 38;
static const long asn_VAL_43_ignore = 1;
static const long asn_VAL_44_id_ReferenceTimeInformationReportingControl = 58;
static const long asn_VAL_44_ignore = 1;
static const long asn_VAL_45_id_ReferenceTimeInformationReport = 57;
static const long asn_VAL_45_ignore = 1;
static const long asn_VAL_46_id_accessSuccess = 39;
static const long asn_VAL_46_ignore = 1;
static const long asn_VAL_47_id_cellTrafficTrace = 40;
static const long asn_VAL_47_ignore = 1;
static const long asn_VAL_48_id_PositioningAssistanceInformationControl = 42;
static const long asn_VAL_48_ignore = 1;
static const long asn_VAL_49_id_PositioningAssistanceInformationFeedback = 43;
static const long asn_VAL_49_ignore = 1;
static const long asn_VAL_50_id_PositioningMeasurementReport = 44;
static const long asn_VAL_50_ignore = 1;
static const long asn_VAL_51_id_PositioningMeasurementAbort = 45;
static const long asn_VAL_51_ignore = 1;
static const long asn_VAL_52_id_PositioningMeasurementFailureIndication = 46;
static const long asn_VAL_52_ignore = 1;
static const long asn_VAL_53_id_PositioningMeasurementUpdate = 47;
static const long asn_VAL_53_ignore = 1;
static const long asn_VAL_54_id_PositioningDeactivation = 51;
static const long asn_VAL_54_ignore = 1;
static const long asn_VAL_55_id_E_CIDMeasurementFailureIndication = 53;
static const long asn_VAL_55_ignore = 1;
static const long asn_VAL_56_id_E_CIDMeasurementReport = 54;
static const long asn_VAL_56_ignore = 1;
static const long asn_VAL_57_id_E_CIDMeasurementTermination = 55;
static const long asn_VAL_57_ignore = 1;
static const long asn_VAL_58_id_PositioningInformationUpdate = 56;
static const long asn_VAL_58_ignore = 1;
static const asn_ioc_cell_t asn_IOS_F1AP_ELEMENTARY_PROCEDURES_1_rows[] = {
	{ "&InitiatingMessage", aioc__type, &asn_DEF_Reset },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ResetAcknowledge },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_1_id_Reset },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_1_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_F1SetupRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_F1SetupResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_F1SetupFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_2_id_F1Setup },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_2_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_GNBDUConfigurationUpdate },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_GNBDUConfigurationUpdateAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_GNBDUConfigurationUpdateFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_3_id_gNBDUConfigurationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_3_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_GNBCUConfigurationUpdate },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_GNBCUConfigurationUpdateAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_GNBCUConfigurationUpdateFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_4_id_gNBCUConfigurationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_4_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_UEContextSetupRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_UEContextSetupResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_UEContextSetupFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_5_id_UEContextSetup },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_5_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_UEContextReleaseCommand },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_UEContextReleaseComplete },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_6_id_UEContextRelease },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_6_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_UEContextModificationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_UEContextModificationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_UEContextModificationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_7_id_UEContextModification },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_7_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_UEContextModificationRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_UEContextModificationConfirm },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_UEContextModificationRefuse },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_8_id_UEContextModificationRequired },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_8_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_WriteReplaceWarningRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_WriteReplaceWarningResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_9_id_WriteReplaceWarning },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_9_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PWSCancelRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_PWSCancelResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_10_id_PWSCancel },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_10_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_GNBDUResourceCoordinationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_GNBDUResourceCoordinationResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_11_id_GNBDUResourceCoordination },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_11_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_F1RemovalRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_F1RemovalResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_F1RemovalFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_12_id_F1Removal },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_12_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_BAPMappingConfiguration },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_BAPMappingConfigurationAcknowledge },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_13_id_BAPMappingConfiguration },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_13_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_GNBDUResourceConfiguration },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_GNBDUResourceConfigurationAcknowledge },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_14_id_GNBDUResourceConfiguration },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_14_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_IABTNLAddressRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_IABTNLAddressResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_15_id_IABTNLAddressAllocation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_15_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_IABUPConfigurationUpdateRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_IABUPConfigurationUpdateResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_IABUPConfigurationUpdateFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_16_id_IABUPConfigurationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_16_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ResourceStatusRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ResourceStatusResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ResourceStatusFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_17_id_resourceStatusReportingInitiation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_17_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PositioningMeasurementRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_PositioningMeasurementResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_PositioningMeasurementFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_18_id_PositioningMeasurementExchange },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_18_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_TRPInformationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_TRPInformationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_TRPInformationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_19_id_TRPInformationExchange },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_19_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PositioningInformationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_PositioningInformationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_PositioningInformationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_20_id_PositioningInformationExchange },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_20_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PositioningActivationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_PositioningActivationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_PositioningActivationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_21_id_PositioningActivation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_21_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_E_CIDMeasurementInitiationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_E_CIDMeasurementInitiationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_E_CIDMeasurementInitiationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_22_id_E_CIDMeasurementInitiation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_22_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ErrorIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_23_id_ErrorIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_23_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_UEContextReleaseRequest },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_24_id_UEContextReleaseRequest },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_24_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_DLRRCMessageTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_25_id_DLRRCMessageTransfer },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_25_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ULRRCMessageTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_26_id_ULRRCMessageTransfer },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_26_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_UEInactivityNotification },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_27_id_UEInactivityNotification },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_27_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PrivateMessage },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_28_id_privateMessage },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_28_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_InitialULRRCMessageTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_29_id_InitialULRRCMessageTransfer },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_29_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_SystemInformationDeliveryCommand },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_30_id_SystemInformationDeliveryCommand },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_30_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_Paging },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_31_id_Paging },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_31_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_Notify },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_32_id_Notify },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_32_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PWSRestartIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_33_id_PWSRestartIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_33_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PWSFailureIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_34_id_PWSFailureIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_34_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_GNBDUStatusIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_35_id_GNBDUStatusIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_35_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_RRCDeliveryReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_36_id_RRCDeliveryReport },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_36_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NetworkAccessRateReduction },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_37_id_NetworkAccessRateReduction },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_37_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_TraceStart },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_38_id_TraceStart },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_38_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_DeactivateTrace },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_39_id_DeactivateTrace },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_39_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_DUCURadioInformationTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_40_id_DUCURadioInformationTransfer },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_40_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_CUDURadioInformationTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_41_id_CUDURadioInformationTransfer },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_41_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ResourceStatusUpdate },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_42_id_resourceStatusReporting },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_42_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_AccessAndMobilityIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_43_id_accessAndMobilityIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_43_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ReferenceTimeInformationReportingControl },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_44_id_ReferenceTimeInformationReportingControl },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_44_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ReferenceTimeInformationReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_45_id_ReferenceTimeInformationReport },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_45_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_AccessSuccess },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_46_id_accessSuccess },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_46_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_CellTrafficTrace },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_47_id_cellTrafficTrace },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_47_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PositioningAssistanceInformationControl },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_48_id_PositioningAssistanceInformationControl },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_48_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PositioningAssistanceInformationFeedback },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_49_id_PositioningAssistanceInformationFeedback },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_49_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PositioningMeasurementReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_50_id_PositioningMeasurementReport },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_50_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PositioningMeasurementAbort },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_51_id_PositioningMeasurementAbort },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_51_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PositioningMeasurementFailureIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_52_id_PositioningMeasurementFailureIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_52_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PositioningMeasurementUpdate },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_53_id_PositioningMeasurementUpdate },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_53_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PositioningDeactivation },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_54_id_PositioningDeactivation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_54_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_E_CIDMeasurementFailureIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_55_id_E_CIDMeasurementFailureIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_55_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_E_CIDMeasurementReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_56_id_E_CIDMeasurementReport },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_56_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_E_CIDMeasurementTerminationCommand },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_57_id_E_CIDMeasurementTermination },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_57_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_PositioningInformationUpdate },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_58_id_PositioningInformationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_58_ignore }
};
static const asn_ioc_set_t asn_IOS_F1AP_ELEMENTARY_PROCEDURES_1[] = {
	58, 5, asn_IOS_F1AP_ELEMENTARY_PROCEDURES_1_rows
};
static int
memb_procedureCode_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_InitiatingMessage_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_F1AP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 4; /* &criticality */
	size_t row;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct InitiatingMessage, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = row + 1;
	        break;
	    }
	}
	
	return result;
}

static int
memb_criticality_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_InitiatingMessage_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_F1AP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 0; /* &InitiatingMessage */
	size_t row;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct InitiatingMessage, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = row + 1;
	        break;
	    }
	}
	
	return result;
}

static int
memb_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_memb_procedureCode_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_procedureCode_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_criticality_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_criticality_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_value_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_value_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_value_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.Reset),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Reset,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Reset"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.F1SetupRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_F1SetupRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"F1SetupRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.GNBDUConfigurationUpdate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GNBDUConfigurationUpdate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"GNBDUConfigurationUpdate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.GNBCUConfigurationUpdate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GNBCUConfigurationUpdate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"GNBCUConfigurationUpdate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.UEContextSetupRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_UEContextSetupRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UEContextSetupRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.UEContextReleaseCommand),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_UEContextReleaseCommand,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UEContextReleaseCommand"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.UEContextModificationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_UEContextModificationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UEContextModificationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.UEContextModificationRequired),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_UEContextModificationRequired,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UEContextModificationRequired"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.WriteReplaceWarningRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_WriteReplaceWarningRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"WriteReplaceWarningRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PWSCancelRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PWSCancelRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PWSCancelRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.GNBDUResourceCoordinationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GNBDUResourceCoordinationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"GNBDUResourceCoordinationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.F1RemovalRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_F1RemovalRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"F1RemovalRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.BAPMappingConfiguration),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_BAPMappingConfiguration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"BAPMappingConfiguration"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.GNBDUResourceConfiguration),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GNBDUResourceConfiguration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"GNBDUResourceConfiguration"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.IABTNLAddressRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_IABTNLAddressRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"IABTNLAddressRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.IABUPConfigurationUpdateRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_IABUPConfigurationUpdateRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"IABUPConfigurationUpdateRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.ResourceStatusRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ResourceStatusRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ResourceStatusRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PositioningMeasurementRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PositioningMeasurementRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PositioningMeasurementRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.TRPInformationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TRPInformationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"TRPInformationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PositioningInformationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PositioningInformationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PositioningInformationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PositioningActivationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PositioningActivationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PositioningActivationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.E_CIDMeasurementInitiationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E_CIDMeasurementInitiationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"E-CIDMeasurementInitiationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.ErrorIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ErrorIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ErrorIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.UEContextReleaseRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_UEContextReleaseRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UEContextReleaseRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.DLRRCMessageTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DLRRCMessageTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"DLRRCMessageTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.ULRRCMessageTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ULRRCMessageTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ULRRCMessageTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.UEInactivityNotification),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_UEInactivityNotification,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UEInactivityNotification"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PrivateMessage),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PrivateMessage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PrivateMessage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.InitialULRRCMessageTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_InitialULRRCMessageTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"InitialULRRCMessageTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.SystemInformationDeliveryCommand),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SystemInformationDeliveryCommand,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SystemInformationDeliveryCommand"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.Paging),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Paging,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Paging"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.Notify),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Notify,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Notify"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PWSRestartIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PWSRestartIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PWSRestartIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PWSFailureIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PWSFailureIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PWSFailureIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.GNBDUStatusIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GNBDUStatusIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"GNBDUStatusIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.RRCDeliveryReport),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RRCDeliveryReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RRCDeliveryReport"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.NetworkAccessRateReduction),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NetworkAccessRateReduction,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"NetworkAccessRateReduction"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.TraceStart),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TraceStart,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"TraceStart"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.DeactivateTrace),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DeactivateTrace,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"DeactivateTrace"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.DUCURadioInformationTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DUCURadioInformationTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"DUCURadioInformationTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.CUDURadioInformationTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CUDURadioInformationTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"CUDURadioInformationTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.ResourceStatusUpdate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ResourceStatusUpdate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ResourceStatusUpdate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.AccessAndMobilityIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AccessAndMobilityIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"AccessAndMobilityIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.ReferenceTimeInformationReportingControl),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ReferenceTimeInformationReportingControl,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ReferenceTimeInformationReportingControl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.ReferenceTimeInformationReport),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ReferenceTimeInformationReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ReferenceTimeInformationReport"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.AccessSuccess),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AccessSuccess,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"AccessSuccess"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.CellTrafficTrace),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CellTrafficTrace,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"CellTrafficTrace"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PositioningAssistanceInformationControl),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PositioningAssistanceInformationControl,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PositioningAssistanceInformationControl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PositioningAssistanceInformationFeedback),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PositioningAssistanceInformationFeedback,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PositioningAssistanceInformationFeedback"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PositioningMeasurementReport),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PositioningMeasurementReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PositioningMeasurementReport"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PositioningMeasurementAbort),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PositioningMeasurementAbort,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PositioningMeasurementAbort"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PositioningMeasurementFailureIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PositioningMeasurementFailureIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PositioningMeasurementFailureIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PositioningMeasurementUpdate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PositioningMeasurementUpdate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PositioningMeasurementUpdate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PositioningDeactivation),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PositioningDeactivation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PositioningDeactivation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.E_CIDMeasurementFailureIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E_CIDMeasurementFailureIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"E-CIDMeasurementFailureIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.E_CIDMeasurementReport),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E_CIDMeasurementReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"E-CIDMeasurementReport"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.E_CIDMeasurementTerminationCommand),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E_CIDMeasurementTerminationCommand,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"E-CIDMeasurementTerminationCommand"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PositioningInformationUpdate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PositioningInformationUpdate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PositioningInformationUpdate"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_value_tag2el_4[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 57 }, /* Reset */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 56 }, /* F1SetupRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 55 }, /* GNBDUConfigurationUpdate */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 54 }, /* GNBCUConfigurationUpdate */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -4, 53 }, /* UEContextSetupRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -5, 52 }, /* UEContextReleaseCommand */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 6, -6, 51 }, /* UEContextModificationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 7, -7, 50 }, /* UEContextModificationRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, -8, 49 }, /* WriteReplaceWarningRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 9, -9, 48 }, /* PWSCancelRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 10, -10, 47 }, /* GNBDUResourceCoordinationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 11, -11, 46 }, /* F1RemovalRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 12, -12, 45 }, /* BAPMappingConfiguration */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 13, -13, 44 }, /* GNBDUResourceConfiguration */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 14, -14, 43 }, /* IABTNLAddressRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 15, -15, 42 }, /* IABUPConfigurationUpdateRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 16, -16, 41 }, /* ResourceStatusRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 17, -17, 40 }, /* PositioningMeasurementRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 18, -18, 39 }, /* TRPInformationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 19, -19, 38 }, /* PositioningInformationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 20, -20, 37 }, /* PositioningActivationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 21, -21, 36 }, /* E-CIDMeasurementInitiationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 22, -22, 35 }, /* ErrorIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 23, -23, 34 }, /* UEContextReleaseRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 24, -24, 33 }, /* DLRRCMessageTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 25, -25, 32 }, /* ULRRCMessageTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 26, -26, 31 }, /* UEInactivityNotification */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 27, -27, 30 }, /* PrivateMessage */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 28, -28, 29 }, /* InitialULRRCMessageTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 29, -29, 28 }, /* SystemInformationDeliveryCommand */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 30, -30, 27 }, /* Paging */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 31, -31, 26 }, /* Notify */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 32, -32, 25 }, /* PWSRestartIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 33, -33, 24 }, /* PWSFailureIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 34, -34, 23 }, /* GNBDUStatusIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 35, -35, 22 }, /* RRCDeliveryReport */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 36, -36, 21 }, /* NetworkAccessRateReduction */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 37, -37, 20 }, /* TraceStart */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 38, -38, 19 }, /* DeactivateTrace */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 39, -39, 18 }, /* DUCURadioInformationTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 40, -40, 17 }, /* CUDURadioInformationTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 41, -41, 16 }, /* ResourceStatusUpdate */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 42, -42, 15 }, /* AccessAndMobilityIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 43, -43, 14 }, /* ReferenceTimeInformationReportingControl */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 44, -44, 13 }, /* ReferenceTimeInformationReport */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 45, -45, 12 }, /* AccessSuccess */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 46, -46, 11 }, /* CellTrafficTrace */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 47, -47, 10 }, /* PositioningAssistanceInformationControl */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 48, -48, 9 }, /* PositioningAssistanceInformationFeedback */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 49, -49, 8 }, /* PositioningMeasurementReport */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 50, -50, 7 }, /* PositioningMeasurementAbort */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 51, -51, 6 }, /* PositioningMeasurementFailureIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 52, -52, 5 }, /* PositioningMeasurementUpdate */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 53, -53, 4 }, /* PositioningDeactivation */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 54, -54, 3 }, /* E-CIDMeasurementFailureIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 55, -55, 2 }, /* E-CIDMeasurementReport */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 56, -56, 1 }, /* E-CIDMeasurementTerminationCommand */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 57, -57, 0 } /* PositioningInformationUpdate */
};
static asn_CHOICE_specifics_t asn_SPC_value_specs_4 = {
	sizeof(struct InitiatingMessage__value),
	offsetof(struct InitiatingMessage__value, _asn_ctx),
	offsetof(struct InitiatingMessage__value, present),
	sizeof(((struct InitiatingMessage__value *)0)->present),
	asn_MAP_value_tag2el_4,
	58,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_value_4 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_value_4,
	58,	/* Elements count */
	&asn_SPC_value_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_InitiatingMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage, procedureCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProcedureCode,
		0,
		{ &asn_OER_memb_procedureCode_constr_2, &asn_PER_memb_procedureCode_constr_2,  memb_procedureCode_constraint_1 },
		0, 0, /* No default value */
		"procedureCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Criticality,
		select_InitiatingMessage_criticality_type,
		{ &asn_OER_memb_criticality_constr_3, &asn_PER_memb_criticality_constr_3,  memb_criticality_constraint_1 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_value_4,
		select_InitiatingMessage_value_type,
		{ &asn_OER_memb_value_constr_4, &asn_PER_memb_value_constr_4,  memb_value_constraint_1 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_InitiatingMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_InitiatingMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* procedureCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_InitiatingMessage_specs_1 = {
	sizeof(struct InitiatingMessage),
	offsetof(struct InitiatingMessage, _asn_ctx),
	asn_MAP_InitiatingMessage_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_InitiatingMessage = {
	"InitiatingMessage",
	"InitiatingMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_InitiatingMessage_tags_1,
	sizeof(asn_DEF_InitiatingMessage_tags_1)
		/sizeof(asn_DEF_InitiatingMessage_tags_1[0]), /* 1 */
	asn_DEF_InitiatingMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_InitiatingMessage_tags_1)
		/sizeof(asn_DEF_InitiatingMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_InitiatingMessage_1,
	3,	/* Elements count */
	&asn_SPC_InitiatingMessage_specs_1	/* Additional specs */
};

