/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-PDU-Descriptions"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_InitiatingMessage_H_
#define	_InitiatingMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProcedureCode.h"
#include "Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "Reset.h"
#include "ResetAcknowledge.h"
#include "F1SetupRequest.h"
#include "F1SetupResponse.h"
#include "F1SetupFailure.h"
#include "GNBDUConfigurationUpdate.h"
#include "GNBDUConfigurationUpdateAcknowledge.h"
#include "GNBDUConfigurationUpdateFailure.h"
#include "GNBCUConfigurationUpdate.h"
#include "GNBCUConfigurationUpdateAcknowledge.h"
#include "GNBCUConfigurationUpdateFailure.h"
#include "UEContextSetupRequest.h"
#include "UEContextSetupResponse.h"
#include "UEContextSetupFailure.h"
#include "UEContextReleaseCommand.h"
#include "UEContextReleaseComplete.h"
#include "UEContextModificationRequest.h"
#include "UEContextModificationResponse.h"
#include "UEContextModificationFailure.h"
#include "UEContextModificationRequired.h"
#include "UEContextModificationConfirm.h"
#include "UEContextModificationRefuse.h"
#include "WriteReplaceWarningRequest.h"
#include "WriteReplaceWarningResponse.h"
#include "PWSCancelRequest.h"
#include "PWSCancelResponse.h"
#include "GNBDUResourceCoordinationRequest.h"
#include "GNBDUResourceCoordinationResponse.h"
#include "F1RemovalRequest.h"
#include "F1RemovalResponse.h"
#include "F1RemovalFailure.h"
#include "BAPMappingConfiguration.h"
#include "BAPMappingConfigurationAcknowledge.h"
#include "BAPMappingConfigurationFailure.h"
#include "GNBDUResourceConfiguration.h"
#include "GNBDUResourceConfigurationAcknowledge.h"
#include "GNBDUResourceConfigurationFailure.h"
#include "IABTNLAddressRequest.h"
#include "IABTNLAddressResponse.h"
#include "IABTNLAddressFailure.h"
#include "IABUPConfigurationUpdateRequest.h"
#include "IABUPConfigurationUpdateResponse.h"
#include "IABUPConfigurationUpdateFailure.h"
#include "ResourceStatusRequest.h"
#include "ResourceStatusResponse.h"
#include "ResourceStatusFailure.h"
#include "PositioningMeasurementRequest.h"
#include "PositioningMeasurementResponse.h"
#include "PositioningMeasurementFailure.h"
#include "TRPInformationRequest.h"
#include "TRPInformationResponse.h"
#include "TRPInformationFailure.h"
#include "PositioningInformationRequest.h"
#include "PositioningInformationResponse.h"
#include "PositioningInformationFailure.h"
#include "PositioningActivationRequest.h"
#include "PositioningActivationResponse.h"
#include "PositioningActivationFailure.h"
#include "E-CIDMeasurementInitiationRequest.h"
#include "E-CIDMeasurementInitiationResponse.h"
#include "E-CIDMeasurementInitiationFailure.h"
#include "ErrorIndication.h"
#include "UEContextReleaseRequest.h"
#include "DLRRCMessageTransfer.h"
#include "ULRRCMessageTransfer.h"
#include "UEInactivityNotification.h"
#include "PrivateMessage.h"
#include "InitialULRRCMessageTransfer.h"
#include "SystemInformationDeliveryCommand.h"
#include "Paging.h"
#include "Notify.h"
#include "PWSRestartIndication.h"
#include "PWSFailureIndication.h"
#include "GNBDUStatusIndication.h"
#include "RRCDeliveryReport.h"
#include "NetworkAccessRateReduction.h"
#include "TraceStart.h"
#include "DeactivateTrace.h"
#include "DUCURadioInformationTransfer.h"
#include "CUDURadioInformationTransfer.h"
#include "ResourceStatusUpdate.h"
#include "AccessAndMobilityIndication.h"
#include "ReferenceTimeInformationReportingControl.h"
#include "ReferenceTimeInformationReport.h"
#include "AccessSuccess.h"
#include "CellTrafficTrace.h"
#include "PositioningAssistanceInformationControl.h"
#include "PositioningAssistanceInformationFeedback.h"
#include "PositioningMeasurementReport.h"
#include "PositioningMeasurementAbort.h"
#include "PositioningMeasurementFailureIndication.h"
#include "PositioningMeasurementUpdate.h"
#include "PositioningDeactivation.h"
#include "E-CIDMeasurementFailureIndication.h"
#include "E-CIDMeasurementReport.h"
#include "E-CIDMeasurementTerminationCommand.h"
#include "PositioningInformationUpdate.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InitiatingMessage__value_PR {
	InitiatingMessage__value_PR_NOTHING,	/* No components present */
	InitiatingMessage__value_PR_Reset,
	InitiatingMessage__value_PR_F1SetupRequest,
	InitiatingMessage__value_PR_GNBDUConfigurationUpdate,
	InitiatingMessage__value_PR_GNBCUConfigurationUpdate,
	InitiatingMessage__value_PR_UEContextSetupRequest,
	InitiatingMessage__value_PR_UEContextReleaseCommand,
	InitiatingMessage__value_PR_UEContextModificationRequest,
	InitiatingMessage__value_PR_UEContextModificationRequired,
	InitiatingMessage__value_PR_WriteReplaceWarningRequest,
	InitiatingMessage__value_PR_PWSCancelRequest,
	InitiatingMessage__value_PR_GNBDUResourceCoordinationRequest,
	InitiatingMessage__value_PR_F1RemovalRequest,
	InitiatingMessage__value_PR_BAPMappingConfiguration,
	InitiatingMessage__value_PR_GNBDUResourceConfiguration,
	InitiatingMessage__value_PR_IABTNLAddressRequest,
	InitiatingMessage__value_PR_IABUPConfigurationUpdateRequest,
	InitiatingMessage__value_PR_ResourceStatusRequest,
	InitiatingMessage__value_PR_PositioningMeasurementRequest,
	InitiatingMessage__value_PR_TRPInformationRequest,
	InitiatingMessage__value_PR_PositioningInformationRequest,
	InitiatingMessage__value_PR_PositioningActivationRequest,
	InitiatingMessage__value_PR_E_CIDMeasurementInitiationRequest,
	InitiatingMessage__value_PR_ErrorIndication,
	InitiatingMessage__value_PR_UEContextReleaseRequest,
	InitiatingMessage__value_PR_DLRRCMessageTransfer,
	InitiatingMessage__value_PR_ULRRCMessageTransfer,
	InitiatingMessage__value_PR_UEInactivityNotification,
	InitiatingMessage__value_PR_PrivateMessage,
	InitiatingMessage__value_PR_InitialULRRCMessageTransfer,
	InitiatingMessage__value_PR_SystemInformationDeliveryCommand,
	InitiatingMessage__value_PR_Paging,
	InitiatingMessage__value_PR_Notify,
	InitiatingMessage__value_PR_PWSRestartIndication,
	InitiatingMessage__value_PR_PWSFailureIndication,
	InitiatingMessage__value_PR_GNBDUStatusIndication,
	InitiatingMessage__value_PR_RRCDeliveryReport,
	InitiatingMessage__value_PR_NetworkAccessRateReduction,
	InitiatingMessage__value_PR_TraceStart,
	InitiatingMessage__value_PR_DeactivateTrace,
	InitiatingMessage__value_PR_DUCURadioInformationTransfer,
	InitiatingMessage__value_PR_CUDURadioInformationTransfer,
	InitiatingMessage__value_PR_ResourceStatusUpdate,
	InitiatingMessage__value_PR_AccessAndMobilityIndication,
	InitiatingMessage__value_PR_ReferenceTimeInformationReportingControl,
	InitiatingMessage__value_PR_ReferenceTimeInformationReport,
	InitiatingMessage__value_PR_AccessSuccess,
	InitiatingMessage__value_PR_CellTrafficTrace,
	InitiatingMessage__value_PR_PositioningAssistanceInformationControl,
	InitiatingMessage__value_PR_PositioningAssistanceInformationFeedback,
	InitiatingMessage__value_PR_PositioningMeasurementReport,
	InitiatingMessage__value_PR_PositioningMeasurementAbort,
	InitiatingMessage__value_PR_PositioningMeasurementFailureIndication,
	InitiatingMessage__value_PR_PositioningMeasurementUpdate,
	InitiatingMessage__value_PR_PositioningDeactivation,
	InitiatingMessage__value_PR_E_CIDMeasurementFailureIndication,
	InitiatingMessage__value_PR_E_CIDMeasurementReport,
	InitiatingMessage__value_PR_E_CIDMeasurementTerminationCommand,
	InitiatingMessage__value_PR_PositioningInformationUpdate
} InitiatingMessage__value_PR;

/* InitiatingMessage */
typedef struct InitiatingMessage {
	ProcedureCode_t	 procedureCode;
	Criticality_t	 criticality;
	struct InitiatingMessage__value {
		InitiatingMessage__value_PR present;
		union InitiatingMessage__value_u {
			Reset_t	 Reset;
			F1SetupRequest_t	 F1SetupRequest;
			GNBDUConfigurationUpdate_t	 GNBDUConfigurationUpdate;
			GNBCUConfigurationUpdate_t	 GNBCUConfigurationUpdate;
			UEContextSetupRequest_t	 UEContextSetupRequest;
			UEContextReleaseCommand_t	 UEContextReleaseCommand;
			UEContextModificationRequest_t	 UEContextModificationRequest;
			UEContextModificationRequired_t	 UEContextModificationRequired;
			WriteReplaceWarningRequest_t	 WriteReplaceWarningRequest;
			PWSCancelRequest_t	 PWSCancelRequest;
			GNBDUResourceCoordinationRequest_t	 GNBDUResourceCoordinationRequest;
			F1RemovalRequest_t	 F1RemovalRequest;
			BAPMappingConfiguration_t	 BAPMappingConfiguration;
			GNBDUResourceConfiguration_t	 GNBDUResourceConfiguration;
			IABTNLAddressRequest_t	 IABTNLAddressRequest;
			IABUPConfigurationUpdateRequest_t	 IABUPConfigurationUpdateRequest;
			ResourceStatusRequest_t	 ResourceStatusRequest;
			PositioningMeasurementRequest_t	 PositioningMeasurementRequest;
			TRPInformationRequest_t	 TRPInformationRequest;
			PositioningInformationRequest_t	 PositioningInformationRequest;
			PositioningActivationRequest_t	 PositioningActivationRequest;
			E_CIDMeasurementInitiationRequest_t	 E_CIDMeasurementInitiationRequest;
			ErrorIndication_t	 ErrorIndication;
			UEContextReleaseRequest_t	 UEContextReleaseRequest;
			DLRRCMessageTransfer_t	 DLRRCMessageTransfer;
			ULRRCMessageTransfer_t	 ULRRCMessageTransfer;
			UEInactivityNotification_t	 UEInactivityNotification;
			PrivateMessage_t	 PrivateMessage;
			InitialULRRCMessageTransfer_t	 InitialULRRCMessageTransfer;
			SystemInformationDeliveryCommand_t	 SystemInformationDeliveryCommand;
			Paging_t	 Paging;
			Notify_t	 Notify;
			PWSRestartIndication_t	 PWSRestartIndication;
			PWSFailureIndication_t	 PWSFailureIndication;
			GNBDUStatusIndication_t	 GNBDUStatusIndication;
			RRCDeliveryReport_t	 RRCDeliveryReport;
			NetworkAccessRateReduction_t	 NetworkAccessRateReduction;
			TraceStart_t	 TraceStart;
			DeactivateTrace_t	 DeactivateTrace;
			DUCURadioInformationTransfer_t	 DUCURadioInformationTransfer;
			CUDURadioInformationTransfer_t	 CUDURadioInformationTransfer;
			ResourceStatusUpdate_t	 ResourceStatusUpdate;
			AccessAndMobilityIndication_t	 AccessAndMobilityIndication;
			ReferenceTimeInformationReportingControl_t	 ReferenceTimeInformationReportingControl;
			ReferenceTimeInformationReport_t	 ReferenceTimeInformationReport;
			AccessSuccess_t	 AccessSuccess;
			CellTrafficTrace_t	 CellTrafficTrace;
			PositioningAssistanceInformationControl_t	 PositioningAssistanceInformationControl;
			PositioningAssistanceInformationFeedback_t	 PositioningAssistanceInformationFeedback;
			PositioningMeasurementReport_t	 PositioningMeasurementReport;
			PositioningMeasurementAbort_t	 PositioningMeasurementAbort;
			PositioningMeasurementFailureIndication_t	 PositioningMeasurementFailureIndication;
			PositioningMeasurementUpdate_t	 PositioningMeasurementUpdate;
			PositioningDeactivation_t	 PositioningDeactivation;
			E_CIDMeasurementFailureIndication_t	 E_CIDMeasurementFailureIndication;
			E_CIDMeasurementReport_t	 E_CIDMeasurementReport;
			E_CIDMeasurementTerminationCommand_t	 E_CIDMeasurementTerminationCommand;
			PositioningInformationUpdate_t	 PositioningInformationUpdate;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitiatingMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiatingMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_InitiatingMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_InitiatingMessage_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _InitiatingMessage_H_ */
#include <asn_internal.h>
