/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#include "LCS-to-GCS-TranslationAoA.h"

#include "ProtocolExtensionContainer.h"
static int
memb_alpha_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3599)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_beta_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3599)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_gamma_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3599)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_alpha_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 12,  12,  0,  3599 }	/* (0..3599) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_beta_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 12,  12,  0,  3599 }	/* (0..3599) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_gamma_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 12,  12,  0,  3599 }	/* (0..3599) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_LCS_to_GCS_TranslationAoA_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_to_GCS_TranslationAoA, alpha),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_alpha_constr_2,  memb_alpha_constraint_1 },
		0, 0, /* No default value */
		"alpha"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_to_GCS_TranslationAoA, beta),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_beta_constr_3,  memb_beta_constraint_1 },
		0, 0, /* No default value */
		"beta"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_to_GCS_TranslationAoA, gamma),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_gamma_constr_4,  memb_gamma_constraint_1 },
		0, 0, /* No default value */
		"gamma"
		},
	{ ATF_POINTER, 1, offsetof(struct LCS_to_GCS_TranslationAoA, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_10676P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_LCS_to_GCS_TranslationAoA_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_LCS_to_GCS_TranslationAoA_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_to_GCS_TranslationAoA_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* alpha */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* beta */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* gamma */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_LCS_to_GCS_TranslationAoA_specs_1 = {
	sizeof(struct LCS_to_GCS_TranslationAoA),
	offsetof(struct LCS_to_GCS_TranslationAoA, _asn_ctx),
	asn_MAP_LCS_to_GCS_TranslationAoA_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_LCS_to_GCS_TranslationAoA_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LCS_to_GCS_TranslationAoA = {
	"LCS-to-GCS-TranslationAoA",
	"LCS-to-GCS-TranslationAoA",
	&asn_OP_SEQUENCE,
	asn_DEF_LCS_to_GCS_TranslationAoA_tags_1,
	sizeof(asn_DEF_LCS_to_GCS_TranslationAoA_tags_1)
		/sizeof(asn_DEF_LCS_to_GCS_TranslationAoA_tags_1[0]), /* 1 */
	asn_DEF_LCS_to_GCS_TranslationAoA_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_to_GCS_TranslationAoA_tags_1)
		/sizeof(asn_DEF_LCS_to_GCS_TranslationAoA_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LCS_to_GCS_TranslationAoA_1,
	4,	/* Elements count */
	&asn_SPC_LCS_to_GCS_TranslationAoA_specs_1	/* Additional specs */
};

