/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_MeasConfig_H_
#define	_MeasConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasConfig */
typedef OCTET_STRING_t	 MeasConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasConfig;
asn_struct_free_f MeasConfig_free;
asn_struct_print_f MeasConfig_print;
asn_constr_check_f MeasConfig_constraint;
ber_type_decoder_f MeasConfig_decode_ber;
der_type_encoder_f MeasConfig_encode_der;
xer_type_decoder_f MeasConfig_decode_xer;
xer_type_encoder_f MeasConfig_encode_xer;
per_type_decoder_f MeasConfig_decode_uper;
per_type_encoder_f MeasConfig_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasConfig_H_ */
#include <asn_internal.h>
