/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#include "MeasuredResultsValue.h"

static asn_oer_constraints_t asn_OER_type_MeasuredResultsValue_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_MeasuredResultsValue_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_MeasuredResultsValue_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasuredResultsValue, choice.uL_AngleOfArrival),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_AoA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uL-AngleOfArrival"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasuredResultsValue, choice.uL_SRS_RSRP),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_SRS_RSRP,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uL-SRS-RSRP"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasuredResultsValue, choice.uL_RTOA),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_RTOA_Measurement,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uL-RTOA"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasuredResultsValue, choice.gNB_RxTxTimeDiff),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GNB_RxTxTimeDiff,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gNB-RxTxTimeDiff"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasuredResultsValue, choice.choice_extension),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolIE_SingleContainer_120P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"choice-extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_MeasuredResultsValue_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uL-AngleOfArrival */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uL-SRS-RSRP */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* uL-RTOA */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* gNB-RxTxTimeDiff */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* choice-extension */
};
asn_CHOICE_specifics_t asn_SPC_MeasuredResultsValue_specs_1 = {
	sizeof(struct MeasuredResultsValue),
	offsetof(struct MeasuredResultsValue, _asn_ctx),
	offsetof(struct MeasuredResultsValue, present),
	sizeof(((struct MeasuredResultsValue *)0)->present),
	asn_MAP_MeasuredResultsValue_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MeasuredResultsValue = {
	"MeasuredResultsValue",
	"MeasuredResultsValue",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_MeasuredResultsValue_constr_1, &asn_PER_type_MeasuredResultsValue_constr_1, CHOICE_constraint },
	asn_MBR_MeasuredResultsValue_1,
	5,	/* Elements count */
	&asn_SPC_MeasuredResultsValue_specs_1	/* Additional specs */
};

