/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_NPNBroadcastInformation_H_
#define	_NPNBroadcastInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NPN-Broadcast-Information-SNPN.h"
#include "NPN-Broadcast-Information-PNI-NPN.h"
#include "ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NPNBroadcastInformation_PR {
	NPNBroadcastInformation_PR_NOTHING,	/* No components present */
	NPNBroadcastInformation_PR_sNPN_Broadcast_Information,
	NPNBroadcastInformation_PR_pNI_NPN_Broadcast_Information,
	NPNBroadcastInformation_PR_choice_extension
} NPNBroadcastInformation_PR;

/* NPNBroadcastInformation */
typedef struct NPNBroadcastInformation {
	NPNBroadcastInformation_PR present;
	union NPNBroadcastInformation_u {
		NPN_Broadcast_Information_SNPN_t	 sNPN_Broadcast_Information;
		NPN_Broadcast_Information_PNI_NPN_t	 pNI_NPN_Broadcast_Information;
		ProtocolIE_SingleContainer_120P0_t	 choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NPNBroadcastInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NPNBroadcastInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _NPNBroadcastInformation_H_ */
#include <asn_internal.h>
