/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_NPNBroadcastInformation_H_
#define	_NPNBroadcastInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NPNBroadcastInformation_PR {
	NPNBroadcastInformation_PR_NOTHING,	/* No components present */
	NPNBroadcastInformation_PR_sNPN_Broadcast_Information,
	NPNBroadcastInformation_PR_pNI_NPN_Broadcast_Information,
	NPNBroadcastInformation_PR_choice_extension
} NPNBroadcastInformation_PR;

/* Forward declarations */
struct NPN_Broadcast_Information_SNPN;
struct NPN_Broadcast_Information_PNI_NPN;
struct ProtocolIE_SingleContainer;

/* NPNBroadcastInformation */
typedef struct NPNBroadcastInformation {
	NPNBroadcastInformation_PR present;
	union NPNBroadcastInformation_u {
		struct NPN_Broadcast_Information_SNPN	*sNPN_Broadcast_Information;
		struct NPN_Broadcast_Information_PNI_NPN	*pNI_NPN_Broadcast_Information;
		struct ProtocolIE_SingleContainer	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NPNBroadcastInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NPNBroadcastInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _NPNBroadcastInformation_H_ */
#include <asn_internal.h>
