/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_NPNSupportInfo_H_
#define	_NPNSupportInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NPNSupportInfo_PR {
	NPNSupportInfo_PR_NOTHING,	/* No components present */
	NPNSupportInfo_PR_sNPN_Information,
	NPNSupportInfo_PR_choice_extension
} NPNSupportInfo_PR;

/* Forward declarations */
struct ProtocolIE_SingleContainer;

/* NPNSupportInfo */
typedef struct NPNSupportInfo {
	NPNSupportInfo_PR present;
	union NPNSupportInfo_u {
		NID_t	 sNPN_Information;
		struct ProtocolIE_SingleContainer	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NPNSupportInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NPNSupportInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _NPNSupportInfo_H_ */
#include <asn_internal.h>
