/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_NPNSupportInfo_H_
#define	_NPNSupportInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NID.h"
#include "ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NPNSupportInfo_PR {
	NPNSupportInfo_PR_NOTHING,	/* No components present */
	NPNSupportInfo_PR_sNPN_Information,
	NPNSupportInfo_PR_choice_extension
} NPNSupportInfo_PR;

/* NPNSupportInfo */
typedef struct NPNSupportInfo {
	NPNSupportInfo_PR present;
	union NPNSupportInfo_u {
		NID_t	 sNPN_Information;
		ProtocolIE_SingleContainer_120P0_t	 choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NPNSupportInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NPNSupportInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _NPNSupportInfo_H_ */
#include <asn_internal.h>
