/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_NR_PRSBeamInformation_H_
#define	_NR_PRSBeamInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NR-PRSBeamInformationList.h"
#include "LCStoGCSTranslationList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* NR-PRSBeamInformation */
typedef struct NR_PRSBeamInformation {
	NR_PRSBeamInformationList_t	 nR_PRSBeamInformationList;
	LCStoGCSTranslationList_t	 lCStoGCSTranslationList;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_PRSBeamInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NR_PRSBeamInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_PRSBeamInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_PRSBeamInformation_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _NR_PRSBeamInformation_H_ */
#include <asn_internal.h>
