/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_NRPRACHConfigItem_H_
#define	_NRPRACHConfigItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRSCS.h"
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "FreqDomainLength.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPRACHConfigItem__msg1FDM {
	NRPRACHConfigItem__msg1FDM_one	= 0,
	NRPRACHConfigItem__msg1FDM_two	= 1,
	NRPRACHConfigItem__msg1FDM_four	= 2,
	NRPRACHConfigItem__msg1FDM_eight	= 3
	/*
	 * Enumeration is extensible
	 */
} e_NRPRACHConfigItem__msg1FDM;
typedef enum NRPRACHConfigItem__ssb_perRACH_Occasion {
	NRPRACHConfigItem__ssb_perRACH_Occasion_oneEighth	= 0,
	NRPRACHConfigItem__ssb_perRACH_Occasion_oneFourth	= 1,
	NRPRACHConfigItem__ssb_perRACH_Occasion_oneHalf	= 2,
	NRPRACHConfigItem__ssb_perRACH_Occasion_one	= 3,
	NRPRACHConfigItem__ssb_perRACH_Occasion_two	= 4,
	NRPRACHConfigItem__ssb_perRACH_Occasion_four	= 5,
	NRPRACHConfigItem__ssb_perRACH_Occasion_eight	= 6,
	NRPRACHConfigItem__ssb_perRACH_Occasion_sixteen	= 7
	/*
	 * Enumeration is extensible
	 */
} e_NRPRACHConfigItem__ssb_perRACH_Occasion;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* NRPRACHConfigItem */
typedef struct NRPRACHConfigItem {
	NRSCS_t	 nRSCS;
	long	 prachFreqStartfromCarrier;
	long	 msg1FDM;
	long	 parchConfigIndex;
	long	 ssb_perRACH_Occasion;
	FreqDomainLength_t	 freqDomainLength;
	long	 zeroCorrelZoneConfig;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPRACHConfigItem_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_msg1FDM_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ssb_perRACH_Occasion_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPRACHConfigItem;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPRACHConfigItem_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPRACHConfigItem_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _NRPRACHConfigItem_H_ */
#include <asn_internal.h>
