/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_NRUERLFReportContainer_H_
#define	_NRUERLFReportContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NRUERLFReportContainer */
typedef OCTET_STRING_t	 NRUERLFReportContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRUERLFReportContainer;
asn_struct_free_f NRUERLFReportContainer_free;
asn_struct_print_f NRUERLFReportContainer_print;
asn_constr_check_f NRUERLFReportContainer_constraint;
ber_type_decoder_f NRUERLFReportContainer_decode_ber;
der_type_encoder_f NRUERLFReportContainer_encode_der;
xer_type_decoder_f NRUERLFReportContainer_decode_xer;
xer_type_encoder_f NRUERLFReportContainer_encode_xer;
oer_type_decoder_f NRUERLFReportContainer_decode_oer;
oer_type_encoder_f NRUERLFReportContainer_encode_oer;
per_type_decoder_f NRUERLFReportContainer_decode_uper;
per_type_encoder_f NRUERLFReportContainer_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRUERLFReportContainer_H_ */
#include <asn_internal.h>
