/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_NZP_CSI_RS_ResourceID_H_
#define	_NZP_CSI_RS_ResourceID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NZP-CSI-RS-ResourceID */
typedef long	 NZP_CSI_RS_ResourceID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NZP_CSI_RS_ResourceID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NZP_CSI_RS_ResourceID;
asn_struct_free_f NZP_CSI_RS_ResourceID_free;
asn_struct_print_f NZP_CSI_RS_ResourceID_print;
asn_constr_check_f NZP_CSI_RS_ResourceID_constraint;
ber_type_decoder_f NZP_CSI_RS_ResourceID_decode_ber;
der_type_encoder_f NZP_CSI_RS_ResourceID_encode_der;
xer_type_decoder_f NZP_CSI_RS_ResourceID_decode_xer;
xer_type_encoder_f NZP_CSI_RS_ResourceID_encode_xer;
oer_type_decoder_f NZP_CSI_RS_ResourceID_decode_oer;
oer_type_encoder_f NZP_CSI_RS_ResourceID_encode_oer;
per_type_decoder_f NZP_CSI_RS_ResourceID_decode_uper;
per_type_encoder_f NZP_CSI_RS_ResourceID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NZP_CSI_RS_ResourceID_H_ */
#include <asn_internal.h>
