/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_PagingIdentity_H_
#define	_PagingIdentity_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RANUEPagingIdentity.h"
#include "CNUEPagingIdentity.h"
#include "ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PagingIdentity_PR {
	PagingIdentity_PR_NOTHING,	/* No components present */
	PagingIdentity_PR_rANUEPagingIdentity,
	PagingIdentity_PR_cNUEPagingIdentity,
	PagingIdentity_PR_choice_extension
} PagingIdentity_PR;

/* PagingIdentity */
typedef struct PagingIdentity {
	PagingIdentity_PR present;
	union PagingIdentity_u {
		RANUEPagingIdentity_t	 rANUEPagingIdentity;
		CNUEPagingIdentity_t	 cNUEPagingIdentity;
		ProtocolIE_SingleContainer_120P0_t	 choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PagingIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PagingIdentity;

#ifdef __cplusplus
}
#endif

#endif	/* _PagingIdentity_H_ */
#include <asn_internal.h>
