/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_PC5QoSFlowIdentifier_H_
#define	_PC5QoSFlowIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PC5QoSFlowIdentifier */
typedef long	 PC5QoSFlowIdentifier_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PC5QoSFlowIdentifier_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PC5QoSFlowIdentifier;
asn_struct_free_f PC5QoSFlowIdentifier_free;
asn_struct_print_f PC5QoSFlowIdentifier_print;
asn_constr_check_f PC5QoSFlowIdentifier_constraint;
ber_type_decoder_f PC5QoSFlowIdentifier_decode_ber;
der_type_encoder_f PC5QoSFlowIdentifier_encode_der;
xer_type_decoder_f PC5QoSFlowIdentifier_decode_xer;
xer_type_encoder_f PC5QoSFlowIdentifier_encode_xer;
oer_type_decoder_f PC5QoSFlowIdentifier_decode_oer;
oer_type_encoder_f PC5QoSFlowIdentifier_encode_oer;
per_type_decoder_f PC5QoSFlowIdentifier_decode_uper;
per_type_encoder_f PC5QoSFlowIdentifier_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PC5QoSFlowIdentifier_H_ */
#include <asn_internal.h>
