/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_PosBroadcast_H_
#define	_PosBroadcast_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PosBroadcast {
	PosBroadcast_start	= 0,
	PosBroadcast_stop	= 1
	/*
	 * Enumeration is extensible
	 */
} e_PosBroadcast;

/* PosBroadcast */
typedef long	 PosBroadcast_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PosBroadcast;
asn_struct_free_f PosBroadcast_free;
asn_struct_print_f PosBroadcast_print;
asn_constr_check_f PosBroadcast_constraint;
ber_type_decoder_f PosBroadcast_decode_ber;
der_type_encoder_f PosBroadcast_encode_der;
xer_type_decoder_f PosBroadcast_decode_xer;
xer_type_encoder_f PosBroadcast_encode_xer;
per_type_decoder_f PosBroadcast_decode_uper;
per_type_encoder_f PosBroadcast_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PosBroadcast_H_ */
#include <asn_internal.h>
