/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_PosMeasurementQuantities_H_
#define	_PosMeasurementQuantities_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PosMeasurementQuantities_Item;

/* PosMeasurementQuantities */
typedef struct PosMeasurementQuantities {
	A_SEQUENCE_OF(struct PosMeasurementQuantities_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PosMeasurementQuantities_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PosMeasurementQuantities;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PosMeasurementQuantities-Item.h"

#endif	/* _PosMeasurementQuantities_H_ */
#include <asn_internal.h>
