/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#include "PosMeasurementType.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
asn_per_constraints_t asn_PER_type_PosMeasurementType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_PosMeasurementType_value2enum_1[] = {
	{ 0,	9,	"gnb-rx-tx" },
	{ 1,	11,	"ul-srs-rsrp" },
	{ 2,	6,	"ul-aoa" },
	{ 3,	7,	"ul-rtoa" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_PosMeasurementType_enum2value_1[] = {
	0,	/* gnb-rx-tx(0) */
	2,	/* ul-aoa(2) */
	3,	/* ul-rtoa(3) */
	1	/* ul-srs-rsrp(1) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_PosMeasurementType_specs_1 = {
	asn_MAP_PosMeasurementType_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_PosMeasurementType_enum2value_1,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	5,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_PosMeasurementType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_PosMeasurementType = {
	"PosMeasurementType",
	"PosMeasurementType",
	&asn_OP_NativeEnumerated,
	asn_DEF_PosMeasurementType_tags_1,
	sizeof(asn_DEF_PosMeasurementType_tags_1)
		/sizeof(asn_DEF_PosMeasurementType_tags_1[0]), /* 1 */
	asn_DEF_PosMeasurementType_tags_1,	/* Same as above */
	sizeof(asn_DEF_PosMeasurementType_tags_1)
		/sizeof(asn_DEF_PosMeasurementType_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_PosMeasurementType_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_PosMeasurementType_specs_1	/* Additional specs */
};

