/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_PosMeasurementPeriodicity_H_
#define	_PosMeasurementPeriodicity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PosMeasurementPeriodicity {
	PosMeasurementPeriodicity_ms120	= 0,
	PosMeasurementPeriodicity_ms240	= 1,
	PosMeasurementPeriodicity_ms480	= 2,
	PosMeasurementPeriodicity_ms640	= 3,
	PosMeasurementPeriodicity_ms1024	= 4,
	PosMeasurementPeriodicity_ms2048	= 5,
	PosMeasurementPeriodicity_ms5120	= 6,
	PosMeasurementPeriodicity_ms10240	= 7,
	PosMeasurementPeriodicity_min1	= 8,
	PosMeasurementPeriodicity_min6	= 9,
	PosMeasurementPeriodicity_min12	= 10,
	PosMeasurementPeriodicity_min30	= 11,
	PosMeasurementPeriodicity_min60	= 12
	/*
	 * Enumeration is extensible
	 */
} e_PosMeasurementPeriodicity;

/* PosMeasurementPeriodicity */
typedef long	 PosMeasurementPeriodicity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PosMeasurementPeriodicity;
asn_struct_free_f PosMeasurementPeriodicity_free;
asn_struct_print_f PosMeasurementPeriodicity_print;
asn_constr_check_f PosMeasurementPeriodicity_constraint;
ber_type_decoder_f PosMeasurementPeriodicity_decode_ber;
der_type_encoder_f PosMeasurementPeriodicity_encode_der;
xer_type_decoder_f PosMeasurementPeriodicity_decode_xer;
xer_type_encoder_f PosMeasurementPeriodicity_encode_xer;
oer_type_decoder_f PosMeasurementPeriodicity_decode_oer;
oer_type_encoder_f PosMeasurementPeriodicity_encode_oer;
per_type_decoder_f PosMeasurementPeriodicity_decode_uper;
per_type_encoder_f PosMeasurementPeriodicity_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PosMeasurementPeriodicity_H_ */
#include <asn_internal.h>
