/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_PosResourceSetTypePR_H_
#define	_PosResourceSetTypePR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PosResourceSetTypePR__posperiodicSet {
	PosResourceSetTypePR__posperiodicSet_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_PosResourceSetTypePR__posperiodicSet;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* PosResourceSetTypePR */
typedef struct PosResourceSetTypePR {
	long	 posperiodicSet;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PosResourceSetTypePR_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_posperiodicSet_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PosResourceSetTypePR;
extern asn_SEQUENCE_specifics_t asn_SPC_PosResourceSetTypePR_specs_1;
extern asn_TYPE_member_t asn_MBR_PosResourceSetTypePR_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PosResourceSetTypePR_H_ */
#include <asn_internal.h>
