/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_PosReportCharacteristics_H_
#define	_PosReportCharacteristics_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PosReportCharacteristics {
	PosReportCharacteristics_ondemand	= 0,
	PosReportCharacteristics_periodic	= 1
	/*
	 * Enumeration is extensible
	 */
} e_PosReportCharacteristics;

/* PosReportCharacteristics */
typedef long	 PosReportCharacteristics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PosReportCharacteristics;
asn_struct_free_f PosReportCharacteristics_free;
asn_struct_print_f PosReportCharacteristics_print;
asn_constr_check_f PosReportCharacteristics_constraint;
ber_type_decoder_f PosReportCharacteristics_decode_ber;
der_type_encoder_f PosReportCharacteristics_encode_der;
xer_type_decoder_f PosReportCharacteristics_decode_xer;
xer_type_encoder_f PosReportCharacteristics_encode_xer;
per_type_decoder_f PosReportCharacteristics_decode_uper;
per_type_encoder_f PosReportCharacteristics_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PosReportCharacteristics_H_ */
#include <asn_internal.h>
