/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-CommonDataTypes"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 * edited by zyzy
 */


#ifndef	_ProtocolIE_ID_H_
#define	_ProtocolIE_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProtocolIE-ID */
typedef long	 ProtocolIE_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ID;
asn_struct_free_f ProtocolIE_ID_free;
asn_struct_print_f ProtocolIE_ID_print;
asn_constr_check_f ProtocolIE_ID_constraint;
ber_type_decoder_f ProtocolIE_ID_decode_ber;
der_type_encoder_f ProtocolIE_ID_encode_der;
xer_type_decoder_f ProtocolIE_ID_decode_xer;
xer_type_encoder_f ProtocolIE_ID_encode_xer;
per_type_decoder_f ProtocolIE_ID_decode_uper;
per_type_encoder_f ProtocolIE_ID_encode_uper;
#define ProtocolIE_ID_id_AllowedNSSAI	((ProtocolIE_ID_t)0)
#define ProtocolIE_ID_id_CU_Name	((ProtocolIE_ID_t)1) //AMFName
#define ProtocolIE_ID_id_AMFOverloadResponse	((ProtocolIE_ID_t)2)
#define ProtocolIE_ID_id_AMFSetID	((ProtocolIE_ID_t)3)
#define ProtocolIE_ID_id_CU_TNL_Association_Failed_To_Setup_List	((ProtocolIE_ID_t)4) //AMF_TNLAssociationFailedToSetupList
#define ProtocolIE_ID_id_CU_TNL_Association_Setup_List	((ProtocolIE_ID_t)5) //AMF_TNLAssociationSetupList
#define ProtocolIE_ID_id_CU_TNL_Association_To_Add_List	((ProtocolIE_ID_t)6) //AMF_TNLAssociationToAddList
#define ProtocolIE_ID_id_CU_TNL_Association_To_Remove_List	((ProtocolIE_ID_t)7) //AMF_TNLAssociationToRemoveList
#define ProtocolIE_ID_id_CU_TNL_Association_To_Update_List	((ProtocolIE_ID_t)8) //AMF_TNLAssociationToUpdateList
#define ProtocolIE_ID_id_AMFTrafficLoadReductionIndication	((ProtocolIE_ID_t)9)
#define ProtocolIE_ID_id_CU_UE_F1AP_ID	((ProtocolIE_ID_t)10) //AMF_UE_NGAP_ID
#define ProtocolIE_ID_id_AssistanceDataForPaging	((ProtocolIE_ID_t)11)
#define ProtocolIE_ID_id_BroadcastCancelledAreaList	((ProtocolIE_ID_t)12)
#define ProtocolIE_ID_id_BroadcastCompletedAreaList	((ProtocolIE_ID_t)13)
#define ProtocolIE_ID_id_CancelAllWarningMessages	((ProtocolIE_ID_t)14)
#define ProtocolIE_ID_id_Cause	((ProtocolIE_ID_t)15) //
#define ProtocolIE_ID_id_CellIDListForRestart	((ProtocolIE_ID_t)16)
#define ProtocolIE_ID_id_ConcurrentWarningMessageInd	((ProtocolIE_ID_t)17)
#define ProtocolIE_ID_id_CoreNetworkAssistanceInformationForInactive	((ProtocolIE_ID_t)18)
#define ProtocolIE_ID_id_CriticalityDiagnostics	((ProtocolIE_ID_t)19)
#define ProtocolIE_ID_id_DataCodingScheme	((ProtocolIE_ID_t)20)
#define ProtocolIE_ID_id_DefaultPagingDRX	((ProtocolIE_ID_t)21)
#define ProtocolIE_ID_id_DirectForwardingPathAvailability	((ProtocolIE_ID_t)22)
#define ProtocolIE_ID_id_EmergencyAreaIDListForRestart	((ProtocolIE_ID_t)23)
#define ProtocolIE_ID_id_EmergencyFallbackIndicator	((ProtocolIE_ID_t)24)
#define ProtocolIE_ID_id_EUTRA_CGI	((ProtocolIE_ID_t)25)
#define ProtocolIE_ID_id_FiveG_S_TMSI	((ProtocolIE_ID_t)26)
#define ProtocolIE_ID_id_GlobalRANNodeID	((ProtocolIE_ID_t)27)
#define ProtocolIE_ID_id_GUAMI	((ProtocolIE_ID_t)28)
#define ProtocolIE_ID_id_HandoverType	((ProtocolIE_ID_t)29)
#define ProtocolIE_ID_id_IMSVoiceSupportIndicator	((ProtocolIE_ID_t)30)
#define ProtocolIE_ID_id_IndexToRFSP	((ProtocolIE_ID_t)31)
#define ProtocolIE_ID_id_InfoOnRecommendedCellsAndRANNodesForPaging	((ProtocolIE_ID_t)32)
#define ProtocolIE_ID_id_LocationReportingRequestType	((ProtocolIE_ID_t)33)
#define ProtocolIE_ID_id_MaskedIMEISV	((ProtocolIE_ID_t)34)
#define ProtocolIE_ID_id_MessageIdentifier	((ProtocolIE_ID_t)35)
#define ProtocolIE_ID_id_MobilityRestrictionList	((ProtocolIE_ID_t)36)
#define ProtocolIE_ID_id_NASC	((ProtocolIE_ID_t)37)
#define ProtocolIE_ID_id_NAS_PDU	((ProtocolIE_ID_t)38)
#define ProtocolIE_ID_id_NASSecurityParametersFromNGRAN	((ProtocolIE_ID_t)39)
#define ProtocolIE_ID_id_NewAMF_UE_NGAP_ID	((ProtocolIE_ID_t)40)
#define ProtocolIE_ID_id_NewSecurityContextInd	((ProtocolIE_ID_t)41)
#define ProtocolIE_ID_id_NGAP_Message	((ProtocolIE_ID_t)42)
#define ProtocolIE_ID_id_NGRAN_CGI	((ProtocolIE_ID_t)43)
#define ProtocolIE_ID_id_NGRANTraceID	((ProtocolIE_ID_t)44)
#define ProtocolIE_ID_id_NR_CGI	((ProtocolIE_ID_t)45)
#define ProtocolIE_ID_id_NRPPa_PDU	((ProtocolIE_ID_t)46)
#define ProtocolIE_ID_id_NumberOfBroadcastsRequested	((ProtocolIE_ID_t)47)
#define ProtocolIE_ID_id_OldAMF	((ProtocolIE_ID_t)48)
#define ProtocolIE_ID_id_OverloadStartNSSAIList	((ProtocolIE_ID_t)49)
#define ProtocolIE_ID_id_PagingDRX	((ProtocolIE_ID_t)50)
#define ProtocolIE_ID_id_PagingOrigin	((ProtocolIE_ID_t)51)
#define ProtocolIE_ID_id_PagingPriority	((ProtocolIE_ID_t)52)
#define ProtocolIE_ID_id_PLMNSupportList	((ProtocolIE_ID_t)80)
#define ProtocolIE_ID_id_PWS_Failed_NR_CGI_List	((ProtocolIE_ID_t)81) //PWSFailedCellIDList
#define ProtocolIE_ID_id_RANNodeName	((ProtocolIE_ID_t)82)
#define ProtocolIE_ID_id_RANPagingPriority	((ProtocolIE_ID_t)83)
#define ProtocolIE_ID_id_RANStatusTransfer_TransparentContainer	((ProtocolIE_ID_t)84)
#define ProtocolIE_ID_id_DU_UE_F1AP_ID	((ProtocolIE_ID_t)85) //RAN_UE_NGAP_ID
#define ProtocolIE_ID_id_RelativeAMFCapacity	((ProtocolIE_ID_t)86)
#define ProtocolIE_ID_id_RepetitionPeriod	((ProtocolIE_ID_t)87)
#define ProtocolIE_ID_id_ResetType	((ProtocolIE_ID_t)88) //ResetType
#define ProtocolIE_ID_id_RoutingID	((ProtocolIE_ID_t)89) //RoutingID
#define ProtocolIE_ID_id_RRCEstablishmentCause	((ProtocolIE_ID_t)90)
#define ProtocolIE_ID_id_RRCInactiveTransitionReportRequest	((ProtocolIE_ID_t)91)
#define ProtocolIE_ID_id_RRCState	((ProtocolIE_ID_t)92)
#define ProtocolIE_ID_id_SecurityContext	((ProtocolIE_ID_t)93)
#define ProtocolIE_ID_id_SecurityKey	((ProtocolIE_ID_t)94)
#define ProtocolIE_ID_id_SerialNumber	((ProtocolIE_ID_t)95)
#define ProtocolIE_ID_id_ServedGUAMIList	((ProtocolIE_ID_t)96)
#define ProtocolIE_ID_id_SliceSupportList	((ProtocolIE_ID_t)97)
#define ProtocolIE_ID_id_SONConfigurationTransferDL	((ProtocolIE_ID_t)98)
#define ProtocolIE_ID_id_SONConfigurationTransferUL	((ProtocolIE_ID_t)99)
#define ProtocolIE_ID_id_SourceAMF_UE_NGAP_ID	((ProtocolIE_ID_t)100)
#define ProtocolIE_ID_id_SourceToTarget_TransparentContainer	((ProtocolIE_ID_t)101)
#define ProtocolIE_ID_id_SupportedTAList	((ProtocolIE_ID_t)102)
#define ProtocolIE_ID_id_TAIListForPaging	((ProtocolIE_ID_t)103)
#define ProtocolIE_ID_id_TAIListForRestart	((ProtocolIE_ID_t)104)
#define ProtocolIE_ID_id_TargetID	((ProtocolIE_ID_t)105)
#define ProtocolIE_ID_id_TargetToSource_TransparentContainer	((ProtocolIE_ID_t)106)
#define ProtocolIE_ID_id_TimeToWait	((ProtocolIE_ID_t)107)
#define ProtocolIE_ID_id_TraceActivation	((ProtocolIE_ID_t)108)
#define ProtocolIE_ID_id_TraceCollectionEntityIPAddress	((ProtocolIE_ID_t)109)
#define ProtocolIE_ID_id_UEAggregateMaximumBitRate	((ProtocolIE_ID_t)110)
#define ProtocolIE_ID_id_UE_associatedLogicalNG_connectionList	((ProtocolIE_ID_t)111)
#define ProtocolIE_ID_id_UEContextRequest	((ProtocolIE_ID_t)112)
#define ProtocolIE_ID_id_UE_NGAP_IDs	((ProtocolIE_ID_t)114)
#define ProtocolIE_ID_id_UEPagingIdentity	((ProtocolIE_ID_t)115)
#define ProtocolIE_ID_id_UEPresenceInAreaOfInterestList	((ProtocolIE_ID_t)116)
#define ProtocolIE_ID_id_UERadioCapability	((ProtocolIE_ID_t)117)
#define ProtocolIE_ID_id_UERadioCapabilityForPaging	((ProtocolIE_ID_t)118)
#define ProtocolIE_ID_id_UESecurityCapabilities	((ProtocolIE_ID_t)119)
#define ProtocolIE_ID_id_UnavailableGUAMIList	((ProtocolIE_ID_t)120)
#define ProtocolIE_ID_id_UserLocationInformation	((ProtocolIE_ID_t)121)
#define ProtocolIE_ID_id_WarningAreaList	((ProtocolIE_ID_t)122)
#define ProtocolIE_ID_id_WarningMessageContents	((ProtocolIE_ID_t)123)
#define ProtocolIE_ID_id_WarningSecurityInfo	((ProtocolIE_ID_t)124)
#define ProtocolIE_ID_id_WarningType	((ProtocolIE_ID_t)125)
#define ProtocolIE_ID_id_AdditionalUL_NGU_UP_TNLInformation	((ProtocolIE_ID_t)126)
#define ProtocolIE_ID_id_DataForwardingNotPossible	((ProtocolIE_ID_t)127)
#define ProtocolIE_ID_id_DL_NGU_UP_TNLInformation	((ProtocolIE_ID_t)128)
#define ProtocolIE_ID_id_NetworkInstance	((ProtocolIE_ID_t)129)
#define ProtocolIE_ID_id_PDUSessionAggregateMaximumBitRate	((ProtocolIE_ID_t)130)
#define ProtocolIE_ID_id_PDUSessionResourceFailedToModifyListModCfm	((ProtocolIE_ID_t)131)
#define ProtocolIE_ID_id_PDUSessionResourceFailedToSetupListCxtFail	((ProtocolIE_ID_t)132)
#define ProtocolIE_ID_id_PDUSessionResourceListCxtRelReq	((ProtocolIE_ID_t)133)
#define ProtocolIE_ID_id_PDUSessionType	((ProtocolIE_ID_t)134)
#define ProtocolIE_ID_id_QosFlowAddOrModifyRequestList	((ProtocolIE_ID_t)135)
#define ProtocolIE_ID_id_QosFlowSetupRequestList	((ProtocolIE_ID_t)136)
#define ProtocolIE_ID_id_QosFlowToReleaseList	((ProtocolIE_ID_t)137)
#define ProtocolIE_ID_id_SecurityIndication	((ProtocolIE_ID_t)138)
#define ProtocolIE_ID_id_UL_NGU_UP_TNLInformation	((ProtocolIE_ID_t)139)
#define ProtocolIE_ID_id_UL_NGU_UP_TNLModifyList	((ProtocolIE_ID_t)140)
#define ProtocolIE_ID_id_WarningAreaCoordinates	((ProtocolIE_ID_t)141)
#define ProtocolIE_ID_id_PDUSessionResourceSecondaryRATUsageList	((ProtocolIE_ID_t)142)
#define ProtocolIE_ID_id_HandoverFlag	((ProtocolIE_ID_t)143)
#define ProtocolIE_ID_id_SecondaryRATUsageInformation	((ProtocolIE_ID_t)144)
#define ProtocolIE_ID_id_PDUSessionResourceReleaseResponseTransfer	((ProtocolIE_ID_t)145)
#define ProtocolIE_ID_id_RedirectionVoiceFallback	((ProtocolIE_ID_t)146)
#define ProtocolIE_ID_id_UERetentionInformation	((ProtocolIE_ID_t)147)
#define ProtocolIE_ID_id_S_NSSAI	((ProtocolIE_ID_t)148)
#define ProtocolIE_ID_id_PSCellInformation	((ProtocolIE_ID_t)149)
#define ProtocolIE_ID_id_LastEUTRAN_PLMNIdentity	((ProtocolIE_ID_t)150)
#define ProtocolIE_ID_id_MaximumIntegrityProtectedDataRate_DL	((ProtocolIE_ID_t)151)
#define ProtocolIE_ID_id_AdditionalDLForwardingUPTNLInformation	((ProtocolIE_ID_t)152)
#define ProtocolIE_ID_id_AdditionalDLUPTNLInformationForHOList	((ProtocolIE_ID_t)153)
#define ProtocolIE_ID_id_AdditionalNGU_UP_TNLInformation	((ProtocolIE_ID_t)154)
#define ProtocolIE_ID_id_AdditionalDLQosFlowPerTNLInformation	((ProtocolIE_ID_t)155)
#define ProtocolIE_ID_id_SecurityResult	((ProtocolIE_ID_t)156)
#define ProtocolIE_ID_id_ENDC_SONConfigurationTransferDL	((ProtocolIE_ID_t)157)
#define ProtocolIE_ID_id_ENDC_SONConfigurationTransferUL	((ProtocolIE_ID_t)158)
#define ProtocolIE_ID_id_OldAssociatedQosFlowList_ULendmarkerexpected	((ProtocolIE_ID_t)159)
#define ProtocolIE_ID_id_CNTypeRestrictionsForEquivalent	((ProtocolIE_ID_t)160)
#define ProtocolIE_ID_id_CNTypeRestrictionsForServing	((ProtocolIE_ID_t)161)
#define ProtocolIE_ID_id_NewGUAMI	((ProtocolIE_ID_t)162)
#define ProtocolIE_ID_id_ULForwarding	((ProtocolIE_ID_t)163)
#define ProtocolIE_ID_id_ULForwardingUP_TNLInformation	((ProtocolIE_ID_t)164)
#define ProtocolIE_ID_id_CNAssistedRANTuning	((ProtocolIE_ID_t)165)
#define ProtocolIE_ID_id_CommonNetworkInstance	((ProtocolIE_ID_t)166)
#define ProtocolIE_ID_id_NGRAN_TNLAssociationToRemoveList	((ProtocolIE_ID_t)167)
#define ProtocolIE_ID_id_TNLAssociationTransportLayerAddressNGRAN	((ProtocolIE_ID_t)168)
#define ProtocolIE_ID_id_EndpointIPAddressAndPort	((ProtocolIE_ID_t)169)
#define ProtocolIE_ID_id_LocationReportingAdditionalInfo	((ProtocolIE_ID_t)170)
#define ProtocolIE_ID_id_SourceToTarget_AMFInformationReroute	((ProtocolIE_ID_t)171)
#define ProtocolIE_ID_id_AdditionalULForwardingUPTNLInformation	((ProtocolIE_ID_t)172)
#define ProtocolIE_ID_id_SCTP_TLAs	((ProtocolIE_ID_t)173)
#define ProtocolIE_ID_id_SelectedPLMNIdentity	((ProtocolIE_ID_t)174)

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_ID_H_ */
#include <asn_internal.h>
