/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-Containers"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#include "ProtocolIE-Container.h"

#include "ProtocolIE-Field.h"
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_10639P0_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ProtocolIE_Container_10639P0_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ProtocolIE_Field_10645P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_10639P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_10639P0_specs_1 = {
	sizeof(struct ProtocolIE_Container_10639P0),
	offsetof(struct ProtocolIE_Container_10639P0, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_10639P0 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_10639P0_tags_1,
	sizeof(asn_DEF_ProtocolIE_Container_10639P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_Container_10639P0_tags_1[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_10639P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_10639P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_Container_10639P0_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_ProtocolIE_Container_10639P0_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_10639P0_1,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_10639P0_specs_1	/* Additional specs */
};

