/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-Containers"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_ProtocolIE_SingleContainer_H_
#define	_ProtocolIE_SingleContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-Field.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ProtocolIE-SingleContainer */
typedef ProtocolIE_Field_10645P0_t	 ProtocolIE_SingleContainer_10642P0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_10642P0;
asn_struct_free_f ProtocolIE_SingleContainer_10642P0_free;
asn_struct_print_f ProtocolIE_SingleContainer_10642P0_print;
asn_constr_check_f ProtocolIE_SingleContainer_10642P0_constraint;
ber_type_decoder_f ProtocolIE_SingleContainer_10642P0_decode_ber;
der_type_encoder_f ProtocolIE_SingleContainer_10642P0_encode_der;
xer_type_decoder_f ProtocolIE_SingleContainer_10642P0_decode_xer;
xer_type_encoder_f ProtocolIE_SingleContainer_10642P0_encode_xer;
per_type_decoder_f ProtocolIE_SingleContainer_10642P0_decode_uper;
per_type_encoder_f ProtocolIE_SingleContainer_10642P0_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_SingleContainer_H_ */
#include <asn_internal.h>
