/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_PRSMuting_H_
#define	_PRSMuting_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PRSMutingOption1.h"
#include "PRSMutingOption2.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* PRSMuting */
typedef struct PRSMuting {
	PRSMutingOption1_t	 pRSMutingOption1;
	PRSMutingOption2_t	 pRSMutingOption2;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PRSMuting_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PRSMuting;
extern asn_SEQUENCE_specifics_t asn_SPC_PRSMuting_specs_1;
extern asn_TYPE_member_t asn_MBR_PRSMuting_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _PRSMuting_H_ */
#include <asn_internal.h>
