/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#include "ReferenceSignal.h"

#include "SSB.h"
#include "DL-PRS.h"
#include "ProtocolIE-SingleContainer.h"
asn_per_constraints_t asn_PER_type_ReferenceSignal_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ReferenceSignal_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReferenceSignal, choice.nZP_CSI_RS),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NZP_CSI_RS_ResourceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nZP-CSI-RS"
		},
	{ ATF_POINTER, 0, offsetof(struct ReferenceSignal, choice.sSB),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SSB,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sSB"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReferenceSignal, choice.sRS),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SRSResourceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sRS"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReferenceSignal, choice.positioningSRS),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SRSPosResourceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"positioningSRS"
		},
	{ ATF_POINTER, 0, offsetof(struct ReferenceSignal, choice.dL_PRS),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DL_PRS,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dL-PRS"
		},
	{ ATF_POINTER, 0, offsetof(struct ReferenceSignal, choice.choice_extension),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolIE_SingleContainer_10642P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"choice-extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ReferenceSignal_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nZP-CSI-RS */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sSB */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sRS */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* positioningSRS */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* dL-PRS */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* choice-extension */
};
asn_CHOICE_specifics_t asn_SPC_ReferenceSignal_specs_1 = {
	sizeof(struct ReferenceSignal),
	offsetof(struct ReferenceSignal, _asn_ctx),
	offsetof(struct ReferenceSignal, present),
	sizeof(((struct ReferenceSignal *)0)->present),
	asn_MAP_ReferenceSignal_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ReferenceSignal = {
	"ReferenceSignal",
	"ReferenceSignal",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ReferenceSignal_constr_1, CHOICE_constraint },
	asn_MBR_ReferenceSignal_1,
	6,	/* Elements count */
	&asn_SPC_ReferenceSignal_specs_1	/* Additional specs */
};

