/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_ReportingPeriodicity_H_
#define	_ReportingPeriodicity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReportingPeriodicity {
	ReportingPeriodicity_ms500	= 0,
	ReportingPeriodicity_ms1000	= 1,
	ReportingPeriodicity_ms2000	= 2,
	ReportingPeriodicity_ms5000	= 3,
	ReportingPeriodicity_ms10000	= 4
	/*
	 * Enumeration is extensible
	 */
} e_ReportingPeriodicity;

/* ReportingPeriodicity */
typedef long	 ReportingPeriodicity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportingPeriodicity;
asn_struct_free_f ReportingPeriodicity_free;
asn_struct_print_f ReportingPeriodicity_print;
asn_constr_check_f ReportingPeriodicity_constraint;
ber_type_decoder_f ReportingPeriodicity_decode_ber;
der_type_encoder_f ReportingPeriodicity_encode_der;
xer_type_decoder_f ReportingPeriodicity_decode_xer;
xer_type_encoder_f ReportingPeriodicity_encode_xer;
per_type_decoder_f ReportingPeriodicity_decode_uper;
per_type_encoder_f ReportingPeriodicity_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportingPeriodicity_H_ */
#include <asn_internal.h>
