/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_Requested_PDCCH_BlindDetectionSCG_H_
#define	_Requested_PDCCH_BlindDetectionSCG_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Requested-PDCCH-BlindDetectionSCG */
typedef OCTET_STRING_t	 Requested_PDCCH_BlindDetectionSCG_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Requested_PDCCH_BlindDetectionSCG;
asn_struct_free_f Requested_PDCCH_BlindDetectionSCG_free;
asn_struct_print_f Requested_PDCCH_BlindDetectionSCG_print;
asn_constr_check_f Requested_PDCCH_BlindDetectionSCG_constraint;
ber_type_decoder_f Requested_PDCCH_BlindDetectionSCG_decode_ber;
der_type_encoder_f Requested_PDCCH_BlindDetectionSCG_encode_der;
xer_type_decoder_f Requested_PDCCH_BlindDetectionSCG_decode_xer;
xer_type_encoder_f Requested_PDCCH_BlindDetectionSCG_encode_xer;
per_type_decoder_f Requested_PDCCH_BlindDetectionSCG_decode_uper;
per_type_encoder_f Requested_PDCCH_BlindDetectionSCG_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Requested_PDCCH_BlindDetectionSCG_H_ */
#include <asn_internal.h>
