/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_RequestType_H_
#define	_RequestType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RequestType {
	RequestType_offer	= 0,
	RequestType_execution	= 1
	/*
	 * Enumeration is extensible
	 */
} e_RequestType;

/* RequestType */
typedef long	 RequestType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RequestType;
asn_struct_free_f RequestType_free;
asn_struct_print_f RequestType_print;
asn_constr_check_f RequestType_constraint;
ber_type_decoder_f RequestType_decode_ber;
der_type_encoder_f RequestType_encode_der;
xer_type_decoder_f RequestType_decode_xer;
xer_type_encoder_f RequestType_encode_xer;
per_type_decoder_f RequestType_decode_uper;
per_type_encoder_f RequestType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RequestType_H_ */
#include <asn_internal.h>
