/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_RequestedSRSTransmissionCharacteristics_H_
#define	_RequestedSRSTransmissionCharacteristics_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "BandwidthSRS.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RequestedSRSTransmissionCharacteristics__resourceType {
	RequestedSRSTransmissionCharacteristics__resourceType_periodic	= 0,
	RequestedSRSTransmissionCharacteristics__resourceType_semi_persistent	= 1,
	RequestedSRSTransmissionCharacteristics__resourceType_aperiodic	= 2
	/*
	 * Enumeration is extensible
	 */
} e_RequestedSRSTransmissionCharacteristics__resourceType;

/* Forward declarations */
struct SRSResourceSetList;
struct SSBInformation;
struct ProtocolExtensionContainer;

/* RequestedSRSTransmissionCharacteristics */
typedef struct RequestedSRSTransmissionCharacteristics {
	long	*numberOfTransmissions	/* OPTIONAL */;
	long	 resourceType;
	BandwidthSRS_t	 bandwidthSRS;
	struct SRSResourceSetList	*sRSResourceSetList	/* OPTIONAL */;
	struct SSBInformation	*sSBInformation	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RequestedSRSTransmissionCharacteristics_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_resourceType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RequestedSRSTransmissionCharacteristics;

#ifdef __cplusplus
}
#endif

#endif	/* _RequestedSRSTransmissionCharacteristics_H_ */
#include <asn_internal.h>
