/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_RLCDuplicationInformation_H_
#define	_RLCDuplicationInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RLCDuplicationStateList.h"
#include "PrimaryPathIndication.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* RLCDuplicationInformation */
typedef struct RLCDuplicationInformation {
	RLCDuplicationStateList_t	 rLCDuplicationStateList;
	PrimaryPathIndication_t	*primaryPathIndication	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RLCDuplicationInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RLCDuplicationInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _RLCDuplicationInformation_H_ */
#include <asn_internal.h>
