/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_SCS_SpecificCarrier_H_
#define	_SCS_SpecificCarrier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SCS_SpecificCarrier__subcarrierSpacing {
	SCS_SpecificCarrier__subcarrierSpacing_kHz15	= 0,
	SCS_SpecificCarrier__subcarrierSpacing_kHz30	= 1,
	SCS_SpecificCarrier__subcarrierSpacing_kHz60	= 2,
	SCS_SpecificCarrier__subcarrierSpacing_kHz120	= 3
	/*
	 * Enumeration is extensible
	 */
} e_SCS_SpecificCarrier__subcarrierSpacing;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* SCS-SpecificCarrier */
typedef struct SCS_SpecificCarrier {
	long	 offsetToCarrier;
	long	 subcarrierSpacing;
	long	 carrierBandwidth;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCS_SpecificCarrier_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_subcarrierSpacing_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SCS_SpecificCarrier;
extern asn_SEQUENCE_specifics_t asn_SPC_SCS_SpecificCarrier_specs_1;
extern asn_TYPE_member_t asn_MBR_SCS_SpecificCarrier_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SCS_SpecificCarrier_H_ */
#include <asn_internal.h>
