/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_SLDRBID_H_
#define	_SLDRBID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SLDRBID */
typedef long	 SLDRBID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SLDRBID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SLDRBID;
asn_struct_free_f SLDRBID_free;
asn_struct_print_f SLDRBID_print;
asn_constr_check_f SLDRBID_constraint;
ber_type_decoder_f SLDRBID_decode_ber;
der_type_encoder_f SLDRBID_encode_der;
xer_type_decoder_f SLDRBID_decode_xer;
xer_type_encoder_f SLDRBID_encode_xer;
per_type_decoder_f SLDRBID_decode_uper;
per_type_encoder_f SLDRBID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SLDRBID_H_ */
#include <asn_internal.h>
