/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_SLDRBs_ToBeModified_Item_H_
#define	_SLDRBs_ToBeModified_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SLDRBID.h"
#include "RLCMode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SLDRBInformation;
struct ProtocolExtensionContainer;

/* SLDRBs-ToBeModified-Item */
typedef struct SLDRBs_ToBeModified_Item {
	SLDRBID_t	 sLDRBID;
	struct SLDRBInformation	*sLDRBInformation	/* OPTIONAL */;
	RLCMode_t	*rLCMode	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SLDRBs_ToBeModified_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SLDRBs_ToBeModified_Item;

#ifdef __cplusplus
}
#endif

#endif	/* _SLDRBs_ToBeModified_Item_H_ */
#include <asn_internal.h>
