/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_SpatialRelationforResourceID_H_
#define	_SpatialRelationforResourceID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SpatialRelationforResourceIDItem;

/* SpatialRelationforResourceID */
typedef struct SpatialRelationforResourceID {
	A_SEQUENCE_OF(struct SpatialRelationforResourceIDItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpatialRelationforResourceID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpatialRelationforResourceID;
extern asn_SET_OF_specifics_t asn_SPC_SpatialRelationforResourceID_specs_1;
extern asn_TYPE_member_t asn_MBR_SpatialRelationforResourceID_1[1];
extern asn_per_constraints_t asn_PER_type_SpatialRelationforResourceID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SpatialRelationforResourceID_H_ */
#include <asn_internal.h>
