/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-PDU-Contents"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#include "SRSType.h"

#include "SemipersistentSRS.h"
#include "AperiodicSRS.h"
#include "ProtocolIE-SingleContainer.h"
static asn_per_constraints_t asn_PER_type_SRSType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_SRSType_1[] = {
	{ ATF_POINTER, 0, offsetof(struct SRSType, choice.semipersistentSRS),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SemipersistentSRS,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"semipersistentSRS"
		},
	{ ATF_POINTER, 0, offsetof(struct SRSType, choice.aperiodicSRS),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AperiodicSRS,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aperiodicSRS"
		},
	{ ATF_POINTER, 0, offsetof(struct SRSType, choice.choice_extension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolIE_SingleContainer_10642P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"choice-extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SRSType_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* semipersistentSRS */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* aperiodicSRS */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* choice-extension */
};
static asn_CHOICE_specifics_t asn_SPC_SRSType_specs_1 = {
	sizeof(struct SRSType),
	offsetof(struct SRSType, _asn_ctx),
	offsetof(struct SRSType, present),
	sizeof(((struct SRSType *)0)->present),
	asn_MAP_SRSType_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SRSType = {
	"SRSType",
	"SRSType",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_SRSType_constr_1, CHOICE_constraint },
	asn_MBR_SRSType_1,
	3,	/* Elements count */
	&asn_SPC_SRSType_specs_1	/* Additional specs */
};

