/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#include "TimeReferenceInformation.h"

#include "ProtocolExtensionContainer.h"
static asn_TYPE_member_t asn_MBR_TimeReferenceInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TimeReferenceInformation, referenceTime),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReferenceTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"referenceTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeReferenceInformation, referenceSFN),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReferenceSFN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"referenceSFN"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeReferenceInformation, uncertainty),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Uncertainty,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uncertainty"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeReferenceInformation, timeInformationType),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeInformationType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeInformationType"
		},
	{ ATF_POINTER, 1, offsetof(struct TimeReferenceInformation, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_10676P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_TimeReferenceInformation_oms_1[] = { 4 };
static const ber_tlv_tag_t asn_DEF_TimeReferenceInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TimeReferenceInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* referenceTime */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* referenceSFN */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* uncertainty */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* timeInformationType */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_TimeReferenceInformation_specs_1 = {
	sizeof(struct TimeReferenceInformation),
	offsetof(struct TimeReferenceInformation, _asn_ctx),
	asn_MAP_TimeReferenceInformation_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_TimeReferenceInformation_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TimeReferenceInformation = {
	"TimeReferenceInformation",
	"TimeReferenceInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_TimeReferenceInformation_tags_1,
	sizeof(asn_DEF_TimeReferenceInformation_tags_1)
		/sizeof(asn_DEF_TimeReferenceInformation_tags_1[0]), /* 1 */
	asn_DEF_TimeReferenceInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_TimeReferenceInformation_tags_1)
		/sizeof(asn_DEF_TimeReferenceInformation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TimeReferenceInformation_1,
	5,	/* Elements count */
	&asn_SPC_TimeReferenceInformation_specs_1	/* Additional specs */
};

