/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_Transport_Layer_Address_Info_H_
#define	_Transport_Layer_Address_Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Transport_UP_Layer_Address_Info_To_Add_List;
struct Transport_UP_Layer_Address_Info_To_Remove_List;
struct ProtocolExtensionContainer;

/* Transport-Layer-Address-Info */
typedef struct Transport_Layer_Address_Info {
	struct Transport_UP_Layer_Address_Info_To_Add_List	*transport_UP_Layer_Address_Info_To_Add_List	/* OPTIONAL */;
	struct Transport_UP_Layer_Address_Info_To_Remove_List	*transport_UP_Layer_Address_Info_To_Remove_List	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Transport_Layer_Address_Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Transport_Layer_Address_Info;

#ifdef __cplusplus
}
#endif

#endif	/* _Transport_Layer_Address_Info_H_ */
#include <asn_internal.h>
