/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_TransmissionStopIndicator_H_
#define	_TransmissionStopIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TransmissionStopIndicator {
	TransmissionStopIndicator_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_TransmissionStopIndicator;

/* TransmissionStopIndicator */
typedef long	 TransmissionStopIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransmissionStopIndicator;
asn_struct_free_f TransmissionStopIndicator_free;
asn_struct_print_f TransmissionStopIndicator_print;
asn_constr_check_f TransmissionStopIndicator_constraint;
ber_type_decoder_f TransmissionStopIndicator_decode_ber;
der_type_encoder_f TransmissionStopIndicator_encode_der;
xer_type_decoder_f TransmissionStopIndicator_decode_xer;
xer_type_encoder_f TransmissionStopIndicator_encode_xer;
per_type_decoder_f TransmissionStopIndicator_decode_uper;
per_type_encoder_f TransmissionStopIndicator_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TransmissionStopIndicator_H_ */
#include <asn_internal.h>
