/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_TRPPositionDefinitionType_H_
#define	_TRPPositionDefinitionType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TRPPositionDefinitionType_PR {
	TRPPositionDefinitionType_PR_NOTHING,	/* No components present */
	TRPPositionDefinitionType_PR_direct,
	TRPPositionDefinitionType_PR_referenced,
	TRPPositionDefinitionType_PR_choice_extension
} TRPPositionDefinitionType_PR;

/* Forward declarations */
struct TRPPositionDirect;
struct TRPPositionReferenced;
struct ProtocolIE_SingleContainer;

/* TRPPositionDefinitionType */
typedef struct TRPPositionDefinitionType {
	TRPPositionDefinitionType_PR present;
	union TRPPositionDefinitionType_u {
		struct TRPPositionDirect	*direct;
		struct TRPPositionReferenced	*referenced;
		struct ProtocolIE_SingleContainer	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TRPPositionDefinitionType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TRPPositionDefinitionType;
extern asn_CHOICE_specifics_t asn_SPC_TRPPositionDefinitionType_specs_1;
extern asn_TYPE_member_t asn_MBR_TRPPositionDefinitionType_1[3];
extern asn_per_constraints_t asn_PER_type_TRPPositionDefinitionType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TRPPositionDefinitionType_H_ */
#include <asn_internal.h>
