/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_TRPType_H_
#define	_TRPType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TRPType {
	TRPType_prsOnlyTP	= 0,
	TRPType_srsOnlyRP	= 1,
	TRPType_tp	= 2,
	TRPType_rp	= 3,
	TRPType_trp	= 4
	/*
	 * Enumeration is extensible
	 */
} e_TRPType;

/* TRPType */
typedef long	 TRPType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TRPType;
asn_struct_free_f TRPType_free;
asn_struct_print_f TRPType_print;
asn_constr_check_f TRPType_constraint;
ber_type_decoder_f TRPType_decode_ber;
der_type_encoder_f TRPType_encode_der;
xer_type_decoder_f TRPType_decode_xer;
xer_type_encoder_f TRPType_encode_xer;
per_type_decoder_f TRPType_decode_uper;
per_type_encoder_f TRPType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TRPType_H_ */
#include <asn_internal.h>
