/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#include "TRPType.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_TRPType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_TRPType_value2enum_1[] = {
	{ 0,	9,	"prsOnlyTP" },
	{ 1,	9,	"srsOnlyRP" },
	{ 2,	2,	"tp" },
	{ 3,	2,	"rp" },
	{ 4,	3,	"trp" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_TRPType_enum2value_1[] = {
	0,	/* prsOnlyTP(0) */
	3,	/* rp(3) */
	1,	/* srsOnlyRP(1) */
	2,	/* tp(2) */
	4	/* trp(4) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_TRPType_specs_1 = {
	asn_MAP_TRPType_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_TRPType_enum2value_1,	/* N => "tag"; sorted by N */
	5,	/* Number of elements in the maps */
	6,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_TRPType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_TRPType = {
	"TRPType",
	"TRPType",
	&asn_OP_NativeEnumerated,
	asn_DEF_TRPType_tags_1,
	sizeof(asn_DEF_TRPType_tags_1)
		/sizeof(asn_DEF_TRPType_tags_1[0]), /* 1 */
	asn_DEF_TRPType_tags_1,	/* Same as above */
	sizeof(asn_DEF_TRPType_tags_1)
		/sizeof(asn_DEF_TRPType_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_TRPType_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_TRPType_specs_1	/* Additional specs */
};

