/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#include "UACCategoryType.h"

#include "UACOperatorDefined.h"
#include "ProtocolIE-SingleContainer.h"
asn_per_constraints_t asn_PER_type_UACCategoryType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_UACCategoryType_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UACCategoryType, choice.uACstandardized),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UACAction,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uACstandardized"
		},
	{ ATF_POINTER, 0, offsetof(struct UACCategoryType, choice.uACOperatorDefined),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UACOperatorDefined,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uACOperatorDefined"
		},
	{ ATF_POINTER, 0, offsetof(struct UACCategoryType, choice.choice_extension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolIE_SingleContainer_10642P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"choice-extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_UACCategoryType_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uACstandardized */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uACOperatorDefined */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* choice-extension */
};
asn_CHOICE_specifics_t asn_SPC_UACCategoryType_specs_1 = {
	sizeof(struct UACCategoryType),
	offsetof(struct UACCategoryType, _asn_ctx),
	offsetof(struct UACCategoryType, present),
	sizeof(((struct UACCategoryType *)0)->present),
	asn_MAP_UACCategoryType_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UACCategoryType = {
	"UACCategoryType",
	"UACCategoryType",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_UACCategoryType_constr_1, CHOICE_constraint },
	asn_MBR_UACCategoryType_1,
	3,	/* Elements count */
	&asn_SPC_UACCategoryType_specs_1	/* Additional specs */
};

