/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_UEAssistanceInformationEUTRA_H_
#define	_UEAssistanceInformationEUTRA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UEAssistanceInformationEUTRA */
typedef OCTET_STRING_t	 UEAssistanceInformationEUTRA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEAssistanceInformationEUTRA;
asn_struct_free_f UEAssistanceInformationEUTRA_free;
asn_struct_print_f UEAssistanceInformationEUTRA_print;
asn_constr_check_f UEAssistanceInformationEUTRA_constraint;
ber_type_decoder_f UEAssistanceInformationEUTRA_decode_ber;
der_type_encoder_f UEAssistanceInformationEUTRA_encode_der;
xer_type_decoder_f UEAssistanceInformationEUTRA_decode_xer;
xer_type_encoder_f UEAssistanceInformationEUTRA_encode_xer;
per_type_decoder_f UEAssistanceInformationEUTRA_decode_uper;
per_type_encoder_f UEAssistanceInformationEUTRA_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UEAssistanceInformationEUTRA_H_ */
#include <asn_internal.h>
