/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "./f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D f1ap`
 */

#ifndef	_UEContextNotRetrievable_H_
#define	_UEContextNotRetrievable_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UEContextNotRetrievable {
	UEContextNotRetrievable_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_UEContextNotRetrievable;

/* UEContextNotRetrievable */
typedef long	 UEContextNotRetrievable_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEContextNotRetrievable;
asn_struct_free_f UEContextNotRetrievable_free;
asn_struct_print_f UEContextNotRetrievable_print;
asn_constr_check_f UEContextNotRetrievable_constraint;
ber_type_decoder_f UEContextNotRetrievable_decode_ber;
der_type_encoder_f UEContextNotRetrievable_encode_der;
xer_type_decoder_f UEContextNotRetrievable_decode_xer;
xer_type_encoder_f UEContextNotRetrievable_encode_xer;
per_type_decoder_f UEContextNotRetrievable_decode_uper;
per_type_encoder_f UEContextNotRetrievable_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UEContextNotRetrievable_H_ */
#include <asn_internal.h>
