/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "f1ap-16.8.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D ../src/asn/f1ap/`
 */

#ifndef	_UL_AoA_H_
#define	_UL_AoA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "ProtocolExtensionContainer.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LCS_to_GCS_TranslationAoA;

/* UL-AoA */
typedef struct UL_AoA {
	long	 azimuthAoA;
	long	*zenithAoA	/* OPTIONAL */;
	struct LCS_to_GCS_TranslationAoA	*lCS_to_GCS_TranslationAoA	/* OPTIONAL */;
	ProtocolExtensionContainer_10676P0_t	 iE_extensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_AoA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_AoA;
extern asn_SEQUENCE_specifics_t asn_SPC_UL_AoA_specs_1;
extern asn_TYPE_member_t asn_MBR_UL_AoA_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _UL_AoA_H_ */
#include <asn_internal.h>
