/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-PDU-Descriptions"
 * 	found in "F1AP-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -gen-PER -D .`
 */

#ifndef	_UnsuccessfulOutcome_H_
#define	_UnsuccessfulOutcome_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProcedureCode.h"
#include "Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "Reset.h"
#include "ResetAcknowledge.h"
#include "F1SetupRequest.h"
#include "F1SetupResponse.h"
#include "F1SetupFailure.h"
#include "GNBDUConfigurationUpdate.h"
#include "GNBDUConfigurationUpdateAcknowledge.h"
#include "GNBDUConfigurationUpdateFailure.h"
#include "GNBCUConfigurationUpdate.h"
#include "GNBCUConfigurationUpdateAcknowledge.h"
#include "GNBCUConfigurationUpdateFailure.h"
#include "UEContextSetupRequest.h"
#include "UEContextSetupResponse.h"
#include "UEContextSetupFailure.h"
#include "UEContextReleaseCommand.h"
#include "UEContextReleaseComplete.h"
#include "UEContextModificationRequest.h"
#include "UEContextModificationResponse.h"
#include "UEContextModificationFailure.h"
#include "UEContextModificationRequired.h"
#include "UEContextModificationConfirm.h"
#include "UEContextModificationRefuse.h"
#include "WriteReplaceWarningRequest.h"
#include "WriteReplaceWarningResponse.h"
#include "PWSCancelRequest.h"
#include "PWSCancelResponse.h"
#include "GNBDUResourceCoordinationRequest.h"
#include "GNBDUResourceCoordinationResponse.h"
#include "F1RemovalRequest.h"
#include "F1RemovalResponse.h"
#include "F1RemovalFailure.h"
#include "BAPMappingConfiguration.h"
#include "BAPMappingConfigurationAcknowledge.h"
#include "GNBDUResourceConfiguration.h"
#include "GNBDUResourceConfigurationAcknowledge.h"
#include "IABTNLAddressRequest.h"
#include "IABTNLAddressResponse.h"
#include "IABUPConfigurationUpdateRequest.h"
#include "IABUPConfigurationUpdateResponse.h"
#include "IABUPConfigurationUpdateFailure.h"
#include "ResourceStatusRequest.h"
#include "ResourceStatusResponse.h"
#include "ResourceStatusFailure.h"
#include "PositioningMeasurementRequest.h"
#include "PositioningMeasurementResponse.h"
#include "PositioningMeasurementFailure.h"
#include "TRPInformationRequest.h"
#include "TRPInformationResponse.h"
#include "TRPInformationFailure.h"
#include "PositioningInformationRequest.h"
#include "PositioningInformationResponse.h"
#include "PositioningInformationFailure.h"
#include "PositioningActivationRequest.h"
#include "PositioningActivationResponse.h"
#include "PositioningActivationFailure.h"
#include "E-CIDMeasurementInitiationRequest.h"
#include "E-CIDMeasurementInitiationResponse.h"
#include "E-CIDMeasurementInitiationFailure.h"
#include "ErrorIndication.h"
#include "UEContextReleaseRequest.h"
#include "DLRRCMessageTransfer.h"
#include "ULRRCMessageTransfer.h"
#include "UEInactivityNotification.h"
#include "PrivateMessage.h"
#include "InitialULRRCMessageTransfer.h"
#include "SystemInformationDeliveryCommand.h"
#include "Paging.h"
#include "Notify.h"
#include "PWSRestartIndication.h"
#include "PWSFailureIndication.h"
#include "GNBDUStatusIndication.h"
#include "RRCDeliveryReport.h"
#include "NetworkAccessRateReduction.h"
#include "TraceStart.h"
#include "DeactivateTrace.h"
#include "DUCURadioInformationTransfer.h"
#include "CUDURadioInformationTransfer.h"
#include "ResourceStatusUpdate.h"
#include "AccessAndMobilityIndication.h"
#include "ReferenceTimeInformationReportingControl.h"
#include "ReferenceTimeInformationReport.h"
#include "AccessSuccess.h"
#include "CellTrafficTrace.h"
#include "PositioningAssistanceInformationControl.h"
#include "PositioningAssistanceInformationFeedback.h"
#include "PositioningMeasurementReport.h"
#include "PositioningMeasurementAbort.h"
#include "PositioningMeasurementFailureIndication.h"
#include "PositioningMeasurementUpdate.h"
#include "PositioningDeactivation.h"
#include "E-CIDMeasurementFailureIndication.h"
#include "E-CIDMeasurementReport.h"
#include "E-CIDMeasurementTerminationCommand.h"
#include "PositioningInformationUpdate.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UnsuccessfulOutcome__value_PR {
	UnsuccessfulOutcome__value_PR_NOTHING,	/* No components present */
	UnsuccessfulOutcome__value_PR_F1SetupFailure,
	UnsuccessfulOutcome__value_PR_GNBDUConfigurationUpdateFailure,
	UnsuccessfulOutcome__value_PR_GNBCUConfigurationUpdateFailure,
	UnsuccessfulOutcome__value_PR_UEContextSetupFailure,
	UnsuccessfulOutcome__value_PR_UEContextModificationFailure,
	UnsuccessfulOutcome__value_PR_UEContextModificationRefuse,
	UnsuccessfulOutcome__value_PR_F1RemovalFailure,
	UnsuccessfulOutcome__value_PR_IABUPConfigurationUpdateFailure,
	UnsuccessfulOutcome__value_PR_ResourceStatusFailure,
	UnsuccessfulOutcome__value_PR_PositioningMeasurementFailure,
	UnsuccessfulOutcome__value_PR_TRPInformationFailure,
	UnsuccessfulOutcome__value_PR_PositioningInformationFailure,
	UnsuccessfulOutcome__value_PR_PositioningActivationFailure,
	UnsuccessfulOutcome__value_PR_E_CIDMeasurementInitiationFailure
} UnsuccessfulOutcome__value_PR;

/* UnsuccessfulOutcome */
typedef struct UnsuccessfulOutcome {
	ProcedureCode_t	 procedureCode;
	Criticality_t	 criticality;
	struct UnsuccessfulOutcome__value {
		UnsuccessfulOutcome__value_PR present;
		union UnsuccessfulOutcome__value_u {
			F1SetupFailure_t	 F1SetupFailure;
			GNBDUConfigurationUpdateFailure_t	 GNBDUConfigurationUpdateFailure;
			GNBCUConfigurationUpdateFailure_t	 GNBCUConfigurationUpdateFailure;
			UEContextSetupFailure_t	 UEContextSetupFailure;
			UEContextModificationFailure_t	 UEContextModificationFailure;
			UEContextModificationRefuse_t	 UEContextModificationRefuse;
			F1RemovalFailure_t	 F1RemovalFailure;
			IABUPConfigurationUpdateFailure_t	 IABUPConfigurationUpdateFailure;
			ResourceStatusFailure_t	 ResourceStatusFailure;
			PositioningMeasurementFailure_t	 PositioningMeasurementFailure;
			TRPInformationFailure_t	 TRPInformationFailure;
			PositioningInformationFailure_t	 PositioningInformationFailure;
			PositioningActivationFailure_t	 PositioningActivationFailure;
			E_CIDMeasurementInitiationFailure_t	 E_CIDMeasurementInitiationFailure;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UnsuccessfulOutcome_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnsuccessfulOutcome;
extern asn_SEQUENCE_specifics_t asn_SPC_UnsuccessfulOutcome_specs_1;
extern asn_TYPE_member_t asn_MBR_UnsuccessfulOutcome_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UnsuccessfulOutcome_H_ */
#include <asn_internal.h>
