mcc: '208'          # Mobile Country Code value
mnc: '99'           # Mobile Network Code value (2 or 3 digits)

CU_ID: '0x000000010'  # NR DU Identity (36-bit)
idLength: 32        # NR DU ID length in bits [22...32]
tac: 1              # Tracking Area Code

f1apIp: 192.168.60.141   # CU's local IP address for F1 Interface (Usually same with local IP)
ngapIp: 192.168.60.14   # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 192.168.60.14    # gNB's local IP address for N3 Interface (Usually same with local IP)

f1apPort: 38472 # Port for F1AP

# List of AMF address information
amfConfigs:
  - address: 192.168.60.11
    port: 38412 # Port for NGAP

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true
